-- v1.7: words 테이블 배치 추가 (difficulty 1~5, 각 100개 = 500개)
-- 기존 517개 + 500개 = 1,017개 (목표 1,500의 67%)

INSERT INTO words (word, definition_ko, definition_en, example_sentence, difficulty, category)
VALUES

-- ── difficulty 1 (A1~A2 기초) ──
('bag', '가방', 'A container for carrying things', 'Put your books in the bag.', 1, 'noun'),
('bed', '침대', 'A piece of furniture for sleeping', 'I sleep in a comfortable bed.', 1, 'noun'),
('bike', '자전거', 'A two-wheeled vehicle', 'She rides her bike to school.', 1, 'noun'),
('bird', '새', 'A feathered animal that can usually fly', 'A bird is singing outside.', 1, 'noun'),
('boat', '배', 'A vessel that travels on water', 'We took a boat across the lake.', 1, 'noun'),
('box', '상자', 'A container with flat sides', 'The toys are in the box.', 1, 'noun'),
('bus', '버스', 'A large vehicle for many passengers', 'I take the bus to work.', 1, 'noun'),
('cake', '케이크', 'A sweet baked dessert', 'She made a chocolate cake.', 1, 'noun'),
('car', '자동차', 'A road vehicle with an engine', 'He drives a red car.', 1, 'noun'),
('chair', '의자', 'A seat with a back and legs', 'Please sit in the chair.', 1, 'noun'),
('cloud', '구름', 'A white or grey mass in the sky', 'Dark clouds mean rain is coming.', 1, 'noun'),
('coin', '동전', 'A metal piece of money', 'I found a coin on the street.', 1, 'noun'),
('cup', '컵', 'A small container for drinking', 'She drank a cup of coffee.', 1, 'noun'),
('desk', '책상', 'A table for working or writing', 'My laptop is on the desk.', 1, 'noun'),
('door', '문', 'An entrance to a room or building', 'Please close the door.', 1, 'noun'),
('egg', '달걀', 'An oval object laid by birds', 'She fried two eggs for breakfast.', 1, 'noun'),
('eye', '눈', 'The organ used for seeing', 'She has beautiful blue eyes.', 1, 'body'),
('face', '얼굴', 'The front part of the head', 'He washed his face in the morning.', 1, 'body'),
('fish', '물고기', 'A cold-blooded aquatic animal', 'We saw colorful fish in the aquarium.', 1, 'noun'),
('floor', '바닥', 'The surface you walk on inside', 'The floor is slippery when wet.', 1, 'noun'),
('flower', '꽃', 'The colorful part of a plant', 'She gave me a beautiful flower.', 1, 'nature'),
('foot', '발', 'The lower part of the leg', 'My foot hurts from walking.', 1, 'body'),
('fork', '포크', 'A utensil for eating with prongs', 'Use a fork to eat your salad.', 1, 'noun'),
('fruit', '과일', 'The edible part of a plant', 'Eat more fruit for good health.', 1, 'daily'),
('gift', '선물', 'Something given to someone', 'He brought a gift for the birthday.', 1, 'noun'),
('girl', '여자아이', 'A female child', 'The girl smiled at me.', 1, 'noun'),
('glass', '유리컵', 'A container for drinking liquids', 'Pour water into the glass.', 1, 'noun'),
('grass', '풀', 'Green plants that cover the ground', 'The grass in the park is green.', 1, 'nature'),
('hair', '머리카락', 'The strands growing on your head', 'She has long black hair.', 1, 'body'),
('hand', '손', 'The part at the end of the arm', 'Raise your hand if you know.', 1, 'body'),
('hat', '모자', 'A covering worn on the head', 'He wears a hat in the sun.', 1, 'noun'),
('home', '집', 'The place where you live', 'I love being at home.', 1, 'daily'),
('horse', '말', 'A large animal used for riding', 'The horse ran across the field.', 1, 'noun'),
('house', '집', 'A building where people live', 'They built a new house.', 1, 'noun'),
('ice', '얼음', 'Frozen water', 'Add some ice to your drink.', 1, 'noun'),
('juice', '주스', 'A liquid from squeezed fruit', 'I drink orange juice in the morning.', 1, 'daily'),
('key', '열쇠', 'A device used to open a lock', 'Don''t forget your house key.', 1, 'noun'),
('knee', '무릎', 'The joint in the middle of the leg', 'He hurt his knee while playing.', 1, 'body'),
('lamp', '램프', 'A device that produces light', 'Turn on the lamp; it''s dark.', 1, 'noun'),
('leaf', '잎', 'A flat green part of a plant', 'The leaf fell from the tree.', 1, 'nature'),
('leg', '다리', 'The limb used for standing and walking', 'He broke his leg skiing.', 1, 'body'),
('light', '빛', 'Energy that makes things visible', 'Turn off the light when you leave.', 1, 'noun'),
('map', '지도', 'A drawing showing an area', 'Check the map to find the route.', 1, 'noun'),
('meat', '고기', 'The flesh of an animal used as food', 'We had grilled meat for dinner.', 1, 'daily'),
('milk', '우유', 'White liquid produced by cows', 'Children should drink milk daily.', 1, 'daily'),
('moon', '달', 'The natural satellite of the Earth', 'The moon is bright tonight.', 1, 'nature'),
('mouth', '입', 'The opening in the face for eating and speaking', 'Open your mouth and say "ah".', 1, 'body'),
('neck', '목', 'The part connecting the head to the body', 'My neck is stiff from sleeping badly.', 1, 'body'),
('nose', '코', 'The organ used for smelling', 'The flower has a nice smell for the nose.', 1, 'body'),
('park', '공원', 'A public area with grass and trees', 'We walked in the park after lunch.', 1, 'noun'),
('pen', '펜', 'A tool for writing with ink', 'May I borrow your pen?', 1, 'noun'),
('picture', '그림', 'A painting or drawing', 'She drew a beautiful picture.', 1, 'noun'),
('pig', '돼지', 'A farm animal with a curly tail', 'The pig rolled in the mud.', 1, 'noun'),
('plant', '식물', 'A living thing that grows in the ground', 'Water the plant every day.', 1, 'nature'),
('plate', '접시', 'A flat dish for food', 'Put the food on the plate.', 1, 'noun'),
('pond', '연못', 'A small area of still water', 'Ducks swim in the pond.', 1, 'nature'),
('rain', '비', 'Water falling from clouds', 'Don''t go out in the rain.', 1, 'nature'),
('river', '강', 'A large natural stream of water', 'We crossed the river by bridge.', 1, 'nature'),
('road', '도로', 'A path for vehicles', 'This road leads to the city.', 1, 'noun'),
('rock', '바위', 'A hard piece of stone', 'She sat on a large rock.', 1, 'nature'),
('room', '방', 'A space within a building', 'My room is on the second floor.', 1, 'noun'),
('sea', '바다', 'A large body of salt water', 'We swam in the sea.', 1, 'nature'),
('shirt', '셔츠', 'A garment worn on the upper body', 'He wore a white shirt to work.', 1, 'noun'),
('shoe', '신발', 'A covering for the foot', 'She bought a new pair of shoes.', 1, 'noun'),
('shop', '가게', 'A place where things are sold', 'The shop closes at nine.', 1, 'noun'),
('shoulder', '어깨', 'The top part of the arm', 'She carried the bag on her shoulder.', 1, 'body'),
('sky', '하늘', 'The space above the earth', 'The sky is clear and blue today.', 1, 'nature'),
('snow', '눈', 'Frozen white flakes from clouds', 'Children love playing in the snow.', 1, 'nature'),
('sock', '양말', 'A cloth covering for the foot', 'He put on clean socks.', 1, 'noun'),
('soup', '국', 'A liquid food made by boiling', 'Have some hot soup for lunch.', 1, 'daily'),
('spoon', '숟가락', 'A utensil for eating liquids', 'Use a spoon for the soup.', 1, 'noun'),
('star', '별', 'A bright object in the night sky', 'The stars are beautiful tonight.', 1, 'nature'),
('stone', '돌', 'A small hard piece of rock', 'She skipped a stone on the lake.', 1, 'nature'),
('street', '거리', 'A road in a city or town', 'The restaurant is on Main Street.', 1, 'noun'),
('sun', '태양', 'The star at the centre of our solar system', 'The sun rises in the east.', 1, 'nature'),
('table', '탁자', 'A flat surface on legs for placing things', 'Set the table for dinner.', 1, 'noun'),
('tooth', '이', 'A hard bone-like structure in the mouth', 'Brush your teeth twice a day.', 1, 'body'),
('town', '마을', 'A small settlement', 'They live in a quiet little town.', 1, 'noun'),
('toy', '장난감', 'An object for children to play with', 'The child played with the toy.', 1, 'noun'),
('tree', '나무', 'A tall plant with a wooden trunk', 'The tree provides nice shade.', 1, 'nature'),
('truck', '트럭', 'A large vehicle for transporting goods', 'A truck blocked the road.', 1, 'noun'),
('wall', '벽', 'A vertical structure forming a room', 'Hang the picture on the wall.', 1, 'noun'),
('water', '물', 'A clear liquid essential for life', 'Drink eight glasses of water a day.', 1, 'daily'),
('wind', '바람', 'Moving air outdoors', 'The wind blew the leaves away.', 1, 'nature'),
('window', '창문', 'An opening in a wall covered by glass', 'Open the window for fresh air.', 1, 'noun'),
('wing', '날개', 'The part of a bird used for flying', 'The bird spread its wings.', 1, 'noun'),
('wood', '나무', 'The hard material from trees', 'The table is made of wood.', 1, 'nature'),
('yard', '마당', 'An outdoor area next to a building', 'The kids play in the yard.', 1, 'noun'),

-- ── difficulty 2 (A2~B1 중학 필수) ──
('accept', '수락하다', 'To agree to receive or do something', 'She accepted the job offer.', 2, 'verb'),
('advice', '조언', 'Suggestions about what to do', 'Can you give me some advice?', 2, 'noun'),
('agree', '동의하다', 'To have the same opinion', 'I agree with your plan.', 2, 'verb'),
('amount', '양', 'A quantity of something', 'A small amount of salt is enough.', 2, 'noun'),
('angry', '화난', 'Feeling strong displeasure', 'He was angry about the delay.', 2, 'adjective'),
('area', '지역', 'A specific place or region', 'This area is known for its beaches.', 2, 'noun'),
('arrive', '도착하다', 'To reach a destination', 'We arrived at the hotel at noon.', 2, 'verb'),
('assistant', '조수', 'A person who helps someone', 'The doctor has a skilled assistant.', 2, 'noun'),
('avoid', '피하다', 'To keep away from something', 'Try to avoid eating late at night.', 2, 'verb'),
('awful', '끔찍한', 'Very bad or unpleasant', 'The weather was awful yesterday.', 2, 'adjective'),
('behavior', '행동', 'The way a person acts', 'Good behavior is expected at school.', 2, 'noun'),
('belong', '속하다', 'To be a member or part of', 'This book belongs to the library.', 2, 'verb'),
('borrow', '빌리다', 'To take something temporarily', 'Can I borrow your umbrella?', 2, 'verb'),
('brave', '용감한', 'Ready to face danger', 'The firefighter was very brave.', 2, 'adjective'),
('brilliant', '훌륭한', 'Extremely clever or talented', 'She had a brilliant idea.', 2, 'adjective'),
('broken', '고장난', 'Not working or in pieces', 'The broken phone needs repair.', 2, 'adjective'),
('busy', '바쁜', 'Having a lot to do', 'I''m too busy to meet today.', 2, 'adjective'),
('calm', '차분한', 'Peaceful, not excited or worried', 'Stay calm in an emergency.', 2, 'adjective'),
('careful', '조심스러운', 'Taking care to avoid mistakes', 'Be careful when crossing the road.', 2, 'adjective'),
('cause', '원인', 'The reason something happens', 'What was the cause of the accident?', 2, 'noun'),
('certainly', '분명히', 'Without doubt', 'I will certainly be there on time.', 2, 'adverb'),
('chance', '기회', 'A possibility or opportunity', 'This is your chance to succeed.', 2, 'noun'),
('change', '변화', 'The act of becoming different', 'The weather can change quickly.', 2, 'noun'),
('charge', '요금', 'A price asked for goods or services', 'Is there an extra charge for delivery?', 2, 'noun'),
('check', '확인하다', 'To examine or verify', 'Check your email for updates.', 2, 'verb'),
('choice', '선택', 'An option you can pick', 'You have a choice between two plans.', 2, 'noun'),
('clearly', '명확하게', 'In a way that is easy to understand', 'Please speak clearly so I can hear.', 2, 'adverb'),
('collect', '수집하다', 'To gather things together', 'He collects old stamps as a hobby.', 2, 'verb'),
('common', '흔한', 'Happening or found often', 'Colds are common in winter.', 2, 'adjective'),
('compare', '비교하다', 'To look at differences and similarities', 'Compare the two prices before buying.', 2, 'verb'),
('complete', '완료하다', 'To finish something', 'Complete the form and submit it.', 2, 'verb'),
('concern', '걱정', 'A feeling of worry', 'There is concern about air quality.', 2, 'noun'),
('connect', '연결하다', 'To join or link together', 'Connect the cable to the device.', 2, 'verb'),
('continue', '계속하다', 'To go on without stopping', 'Please continue with your work.', 2, 'verb'),
('correct', '정확한', 'Free from errors', 'Give the correct answer.', 2, 'adjective'),
('count', '세다', 'To find the total of', 'Count the number of students.', 2, 'verb'),
('cover', '덮다', 'To put something over something else', 'Cover the pot to keep it warm.', 2, 'verb'),
('create', '만들다', 'To make something new', 'She created a beautiful painting.', 2, 'verb'),
('curious', '호기심 많은', 'Eager to learn or know', 'Children are naturally curious.', 2, 'adjective'),
('customer', '고객', 'A person who buys goods or services', 'The customer complained about the service.', 2, 'noun'),
('damage', '손상', 'Harm caused to something', 'The storm caused serious damage.', 2, 'noun'),
('danger', '위험', 'The possibility of harm', 'He was not aware of the danger.', 2, 'noun'),
('dark', '어두운', 'Having little or no light', 'The room was dark and quiet.', 2, 'adjective'),
('dead', '죽은', 'No longer alive', 'The plant is dead; it needs water.', 2, 'adjective'),
('decide', '결정하다', 'To make a choice', 'I decided to stay home today.', 2, 'verb'),
('deep', '깊은', 'Going far down from the surface', 'The lake is very deep.', 2, 'adjective'),
('deliver', '배달하다', 'To bring goods to a person', 'The package will be delivered tomorrow.', 2, 'verb'),
('describe', '묘사하다', 'To give details about something', 'Can you describe what you saw?', 2, 'verb'),
('detail', '세부사항', 'A small but important piece of information', 'Please explain in detail.', 2, 'noun'),
('develop', '발전하다', 'To grow or improve over time', 'The city developed rapidly.', 2, 'verb'),
('different', '다른', 'Not the same as another', 'They come from different cultures.', 2, 'adjective'),
('difficult', '어려운', 'Not easy to do or understand', 'The exam was very difficult.', 2, 'adjective'),
('direction', '방향', 'The course along which something moves', 'Follow the direction signs.', 2, 'noun'),
('dirty', '더러운', 'Not clean', 'Wash your dirty hands before eating.', 2, 'adjective'),
('discover', '발견하다', 'To find something for the first time', 'He discovered a new route.', 2, 'verb'),
('discuss', '논의하다', 'To talk about something with others', 'We discussed the problem together.', 2, 'verb'),
('distance', '거리', 'The length of space between two points', 'The distance from here is five km.', 2, 'noun'),
('double', '두 배의', 'Twice as much', 'The price has doubled this year.', 2, 'adjective'),
('draw', '그리다', 'To make a picture with a pencil or pen', 'She draws beautiful portraits.', 2, 'verb'),
('dream', '꿈', 'Images experienced while sleeping', 'I had a strange dream last night.', 2, 'noun'),
('drive', '운전하다', 'To operate a vehicle', 'He drives to the office every day.', 2, 'verb'),
('drop', '떨어뜨리다', 'To let something fall', 'Don''t drop the glass.', 2, 'verb'),
('during', '동안', 'Throughout a period of time', 'She studied hard during the holidays.', 2, 'adverb'),
('early', '일찍', 'Before the expected time', 'She arrives early every morning.', 2, 'adverb'),
('earn', '벌다', 'To get money by working', 'He earns a good salary.', 2, 'verb'),
('easily', '쉽게', 'Without difficulty', 'She finished the test easily.', 2, 'adverb'),
('effect', '효과', 'A result caused by something', 'Exercise has a positive effect on health.', 2, 'noun'),
('empty', '빈', 'Containing nothing', 'The bottle is empty.', 2, 'adjective'),
('energy', '에너지', 'The ability to do work or be active', 'Solar energy is clean.', 2, 'noun'),
('enjoy', '즐기다', 'To take pleasure in something', 'I enjoy reading novels.', 2, 'verb'),
('enter', '들어가다', 'To go into a place', 'Please enter through the main door.', 2, 'verb'),
('environment', '환경', 'The natural surroundings', 'We must protect the environment.', 2, 'noun'),
('especially', '특히', 'More than usual', 'She loves music, especially jazz.', 2, 'adverb'),
('event', '행사', 'Something that happens', 'The sports event was exciting.', 2, 'noun'),
('exact', '정확한', 'Precise, with no error', 'Give me the exact time.', 2, 'adjective'),
('example', '예시', 'A thing that illustrates a point', 'Give an example of a verb.', 2, 'noun'),
('excellent', '훌륭한', 'Extremely good', 'She got an excellent score.', 2, 'adjective'),
('exciting', '흥미진진한', 'Causing great enthusiasm', 'The game was very exciting.', 2, 'adjective'),
('expect', '기대하다', 'To think something will happen', 'I expect to hear from her soon.', 2, 'verb'),
('experience', '경험', 'Knowledge gained from doing something', 'He has years of experience.', 2, 'noun'),
('explain', '설명하다', 'To make something clear', 'Can you explain this sentence?', 2, 'verb'),
('fact', '사실', 'Something that is true', 'Is that a fact or an opinion?', 2, 'noun'),
('fail', '실패하다', 'To not succeed', 'He failed the driving test twice.', 2, 'verb'),
('familiar', '익숙한', 'Known from experience', 'This song is familiar to me.', 2, 'adjective'),
('famous', '유명한', 'Known by many people', 'She is a famous author.', 2, 'adjective'),
('far', '먼', 'At a great distance', 'The school is not far from here.', 2, 'adjective'),
('fast', '빠른', 'Moving quickly', 'He is a fast runner.', 2, 'adjective'),
('feel', '느끼다', 'To be aware of an emotion', 'I feel happy today.', 2, 'verb'),
('fill', '채우다', 'To put something into a container', 'Fill the bottle with water.', 2, 'verb'),
('finish', '끝내다', 'To complete something', 'Finish your homework before playing.', 2, 'verb'),
('fix', '고치다', 'To repair something broken', 'Can you fix the broken chair?', 2, 'verb'),
('flat', '평평한', 'Having a level surface', 'The road was flat and smooth.', 2, 'adjective'),
('follow', '따르다', 'To go after or obey', 'Follow the instructions carefully.', 2, 'verb'),
('forever', '영원히', 'For all time', 'Friends can be friends forever.', 2, 'adverb'),
('forget', '잊다', 'To fail to remember', 'Don''t forget to call me.', 2, 'verb'),
('forward', '앞으로', 'In the direction you are facing', 'Move forward to the next question.', 2, 'adverb'),
('free', '무료의', 'Costing no money', 'The concert is free for students.', 2, 'adjective'),
('fresh', '신선한', 'Not old or stale', 'Buy fresh vegetables daily.', 2, 'adjective'),
('friendly', '친절한', 'Kind and pleasant', 'The staff are very friendly.', 2, 'adjective'),

-- ── difficulty 3 (B1~B2 고등~대학 입문) ──
('absolutely', '절대적으로', 'Completely and without question', 'I absolutely agree with you.', 3, 'adverb'),
('achieve', '달성하다', 'To successfully complete a goal', 'Hard work helps you achieve success.', 3, 'verb'),
('adapt', '적응하다', 'To change to suit new conditions', 'She adapted quickly to the new job.', 3, 'verb'),
('adequate', '적절한', 'Enough for what is needed', 'Make sure you get adequate sleep.', 3, 'adjective'),
('allocate', '할당하다', 'To give resources for a purpose', 'We need to allocate more time to this.', 3, 'verb'),
('analyze', '분석하다', 'To examine in detail', 'Analyze the data carefully.', 3, 'verb'),
('annual', '연간의', 'Happening once every year', 'The annual report shows strong profits.', 3, 'adjective'),
('apply', '적용하다', 'To use something in a situation', 'Apply this rule to all cases.', 3, 'verb'),
('approach', '접근하다', 'To move closer or deal with', 'Approach the problem with an open mind.', 3, 'verb'),
('appropriate', '적절한', 'Suitable for a situation', 'Choose appropriate clothing for the meeting.', 3, 'adjective'),
('aspect', '측면', 'One part of a situation', 'Consider every aspect of the plan.', 3, 'noun'),
('assess', '평가하다', 'To judge the value or quality', 'The teacher assessed each student''s work.', 3, 'verb'),
('assume', '가정하다', 'To think something is true without proof', 'Don''t assume you know the answer.', 3, 'verb'),
('attitude', '태도', 'A way of thinking or feeling', 'Your positive attitude helps a lot.', 3, 'noun'),
('authority', '권위', 'The power to make decisions', 'The manager has authority over the team.', 3, 'noun'),
('available', '이용 가능한', 'Ready for use or obtainable', 'Is the meeting room available?', 3, 'adjective'),
('background', '배경', 'Someone''s past experience and history', 'Her background is in engineering.', 3, 'noun'),
('benefit', '혜택', 'An advantage or gain', 'Exercise has many health benefits.', 3, 'noun'),
('category', '범주', 'A group of similar things', 'Sort the files into categories.', 3, 'noun'),
('challenge', '도전', 'A difficult task or problem', 'Leadership is a big challenge.', 3, 'noun'),
('circumstance', '상황', 'The conditions around an event', 'The circumstances were unusual.', 3, 'noun'),
('colleague', '동료', 'A person you work with', 'She gets along well with her colleagues.', 3, 'noun'),
('conclude', '결론짓다', 'To decide or end something', 'We concluded that more research is needed.', 3, 'verb'),
('conduct', '수행하다', 'To carry out an activity', 'They will conduct a survey next week.', 3, 'verb'),
('confirm', '확인하다', 'To make sure something is true', 'Can you confirm the meeting time?', 3, 'verb'),
('consequence', '결과', 'A result of an action', 'Think about the consequences first.', 3, 'noun'),
('considerable', '상당한', 'Large in size or amount', 'She has considerable experience.', 3, 'adjective'),
('consistent', '일관성 있는', 'Always behaving the same way', 'Be consistent in your approach.', 3, 'adjective'),
('contribute', '기여하다', 'To give or add to something', 'Everyone must contribute to the project.', 3, 'verb'),
('convince', '설득하다', 'To persuade someone to believe something', 'He convinced me to try the new approach.', 3, 'verb'),
('crucial', '중요한', 'Extremely important', 'Timing is crucial in business.', 3, 'adjective'),
('current', '현재의', 'Existing at the present time', 'What is the current situation?', 3, 'adjective'),
('decade', '10년', 'A period of ten years', 'Technology changed over the last decade.', 3, 'noun'),
('define', '정의하다', 'To explain the meaning of a word', 'Please define the term ''sustainability''.', 3, 'verb'),
('demonstrate', '증명하다', 'To show clearly by example', 'She demonstrated the new technique.', 3, 'verb'),
('despite', '~에도 불구하고', 'Without being affected by something', 'Despite the rain, we went hiking.', 3, 'academic'),
('determine', '결정하다', 'To decide or discover something', 'We need to determine the cause.', 3, 'verb'),
('develop', '발전시키다', 'To improve or create something', 'Develop your skills through practice.', 3, 'verb'),
('discuss', '토의하다', 'To examine by argument', 'We will discuss the issue at the meeting.', 3, 'verb'),
('distinguish', '구별하다', 'To recognize as different', 'Can you distinguish between the two?', 3, 'verb'),
('diverse', '다양한', 'Showing a variety of different types', 'The team has diverse backgrounds.', 3, 'adjective'),
('efficient', '효율적인', 'Achieving results without waste', 'An efficient system saves time and money.', 3, 'adjective'),
('emphasis', '강조', 'Special importance given to something', 'The emphasis is on teamwork.', 3, 'noun'),
('ensure', '보장하다', 'To make certain something happens', 'Ensure the data is backed up.', 3, 'verb'),
('entire', '전체의', 'Whole, with nothing left out', 'The entire team worked overtime.', 3, 'adjective'),
('evaluate', '평가하다', 'To judge the quality of something', 'Evaluate each option carefully.', 3, 'verb'),
('evident', '명백한', 'Clearly seen or understood', 'It was evident that he was nervous.', 3, 'adjective'),
('examine', '검토하다', 'To look at carefully', 'Examine the contract before signing.', 3, 'verb'),
('expand', '확장하다', 'To make or become larger', 'The company plans to expand overseas.', 3, 'verb'),
('expectation', '기대', 'A belief that something will happen', 'Set realistic expectations.', 3, 'noun'),
('experience', '경험하다', 'To have or feel something', 'You will experience a wide variety.', 3, 'verb'),
('expertise', '전문성', 'High skill or knowledge in a field', 'Her expertise in finance is valuable.', 3, 'noun'),
('factor', '요인', 'Something that influences a result', 'Price is a key factor in buying decisions.', 3, 'noun'),
('feature', '특징', 'An important part of something', 'The best feature of this phone is the camera.', 3, 'noun'),
('focus', '집중하다', 'To direct attention to something', 'Focus on the most important tasks first.', 3, 'verb'),
('formal', '공식적인', 'Following official rules and conventions', 'The event requires formal attire.', 3, 'adjective'),
('frequently', '자주', 'Many times or often', 'He frequently travels for business.', 3, 'adverb'),
('fundamental', '기본적인', 'Of central importance', 'Honesty is fundamental to trust.', 3, 'adjective'),
('generate', '발생시키다', 'To produce or create something', 'The new project will generate jobs.', 3, 'verb'),
('global', '세계적인', 'Relating to the whole world', 'Climate change is a global issue.', 3, 'adjective'),
('guideline', '지침', 'A rule or instruction to follow', 'Follow the company guidelines strictly.', 3, 'noun'),
('highlight', '강조하다', 'To emphasize something important', 'He highlighted the key points.', 3, 'verb'),
('identify', '확인하다', 'To recognize or name something', 'Identify the main problem first.', 3, 'verb'),
('impact', '영향', 'A strong effect on something', 'The report had a big impact on the decision.', 3, 'noun'),
('implement', '시행하다', 'To put a plan into action', 'We will implement the new policy.', 3, 'verb'),
('indicate', '나타내다', 'To show or suggest something', 'The data indicates a rising trend.', 3, 'verb'),
('individual', '개인', 'A single person', 'Each individual has unique strengths.', 3, 'noun'),
('industry', '산업', 'A branch of economic activity', 'The tech industry is growing fast.', 3, 'noun'),
('influence', '영향을 미치다', 'To have an effect on something', 'Music can influence your mood.', 3, 'verb'),
('inform', '알리다', 'To tell someone about something', 'Please inform me of any changes.', 3, 'verb'),
('initiative', '주도권', 'The ability to take action independently', 'Take initiative and lead the project.', 3, 'noun'),
('innovate', '혁신하다', 'To introduce new ideas', 'Companies must innovate to stay competitive.', 3, 'verb'),
('insight', '통찰력', 'A deep understanding of something', 'His insight helped solve the problem.', 3, 'noun'),
('integrate', '통합하다', 'To combine two things into one', 'Integrate the new software with existing tools.', 3, 'verb'),
('interact', '상호작용하다', 'To communicate with others', 'Students interact in group discussions.', 3, 'verb'),
('investigate', '조사하다', 'To look into something carefully', 'Police are investigating the incident.', 3, 'verb'),
('involve', '포함하다', 'To include as a part', 'The project involves three departments.', 3, 'verb'),
('issue', '문제', 'An important topic or problem', 'What is the key issue here?', 3, 'noun'),
('justify', '정당화하다', 'To show something is right', 'Can you justify this decision?', 3, 'verb'),
('knowledge', '지식', 'Information and understanding', 'Knowledge is power.', 3, 'noun'),
('launch', '시작하다', 'To start or introduce something', 'They will launch a new product.', 3, 'verb'),
('maintain', '유지하다', 'To keep in good condition', 'Maintain a healthy work-life balance.', 3, 'verb'),
('manage', '관리하다', 'To be in charge of something', 'She manages a team of twenty.', 3, 'verb'),
('method', '방법', 'A way of doing something', 'Use the most effective method.', 3, 'noun'),
('mission', '임무', 'An important task or purpose', 'Our mission is to help customers.', 3, 'noun'),
('monitor', '모니터링하다', 'To watch and check over time', 'Monitor the patient''s condition closely.', 3, 'verb'),
('motivate', '동기부여하다', 'To give a reason to act', 'Good managers motivate their teams.', 3, 'verb'),
('obtain', '획득하다', 'To get something', 'Obtain a permit before starting.', 3, 'verb'),
('objective', '목표', 'A goal or aim', 'Set clear objectives for the project.', 3, 'noun'),
('opportunity', '기회', 'A chance for success', 'Don''t miss this opportunity.', 3, 'noun'),
('overcome', '극복하다', 'To successfully deal with something', 'She overcame her fear of public speaking.', 3, 'verb'),
('participate', '참여하다', 'To take part in something', 'Everyone is encouraged to participate.', 3, 'verb'),
('perception', '인식', 'A way of understanding something', 'Public perception of the brand improved.', 3, 'noun'),
('perspective', '관점', 'A particular way of thinking', 'Consider it from a different perspective.', 3, 'noun'),
('potential', '가능성', 'The ability to develop in the future', 'This idea has great potential.', 3, 'noun'),
('priority', '우선순위', 'The most important thing', 'Customer satisfaction is our top priority.', 3, 'noun'),

-- ── difficulty 4 (B2~C1 대학 학술 어휘) ──
('abstract', '추상적인', 'Existing as an idea, not a physical thing', 'The concept is too abstract to grasp.', 4, 'adjective'),
('accumulate', '축적하다', 'To gather more and more over time', 'Knowledge accumulates with experience.', 4, 'verb'),
('acute', '날카로운', 'Very strong or severe', 'She felt acute pain in her back.', 4, 'adjective'),
('adequate', '충분한', 'Sufficient for the purpose', 'Ensure adequate funding before starting.', 4, 'adjective'),
('adhere', '준수하다', 'To follow rules or beliefs strictly', 'Always adhere to ethical standards.', 4, 'verb'),
('adjacent', '인접한', 'Next to or very near something', 'The café is adjacent to the library.', 4, 'adjective'),
('advocate', '주장하다', 'To publicly support something', 'She advocates for environmental reform.', 4, 'verb'),
('aggregate', '합계', 'A total formed by combining elements', 'The aggregate score was impressive.', 4, 'noun'),
('allegation', '주장', 'A claim that someone did wrong', 'The allegation was denied by the company.', 4, 'noun'),
('alleviate', '완화하다', 'To make suffering less severe', 'Medication can alleviate the pain.', 4, 'verb'),
('ambiguous', '모호한', 'Open to more than one interpretation', 'The contract language was ambiguous.', 4, 'adjective'),
('amplify', '증폭시키다', 'To make larger or more powerful', 'The speaker amplified the sound.', 4, 'verb'),
('analogy', '유추', 'A comparison between two things', 'She used an analogy to explain the idea.', 4, 'noun'),
('arbitrary', '임의적인', 'Based on random choice', 'The decision seemed arbitrary and unfair.', 4, 'adjective'),
('articulate', '분명히 말하다', 'To express thoughts clearly', 'He articulated his concerns well.', 4, 'verb'),
('assert', '주장하다', 'To state something confidently', 'She asserted her right to speak.', 4, 'verb'),
('attribute', '귀속시키다', 'To say something is caused by', 'Success can be attributed to hard work.', 4, 'verb'),
('augment', '증대시키다', 'To make something larger or stronger', 'Technology augments human ability.', 4, 'verb'),
('authentic', '진본의', 'Genuine, not a copy', 'The museum displays authentic artifacts.', 4, 'adjective'),
('autonomy', '자율성', 'Freedom to act independently', 'Employees value autonomy at work.', 4, 'noun'),
('bias', '편견', 'An unfair preference for one thing', 'Be aware of confirmation bias.', 4, 'noun'),
('brevity', '간결함', 'Being short and concise', 'In emails, brevity is appreciated.', 4, 'noun'),
('capability', '능력', 'The ability to do something', 'Assess the team''s capabilities first.', 4, 'noun'),
('coherent', '일관된', 'Logical and well-organized', 'Write a coherent argument.', 4, 'adjective'),
('collaborate', '협력하다', 'To work together on something', 'The teams collaborated on the project.', 4, 'verb'),
('commodify', '상품화하다', 'To treat something as a commercial product', 'Social media has commodified attention.', 4, 'verb'),
('complex', '복잡한', 'Made of many connected parts', 'The issue is more complex than it looks.', 4, 'adjective'),
('comprehensive', '포괄적인', 'Including all aspects', 'A comprehensive review is needed.', 4, 'adjective'),
('concede', '인정하다', 'To admit that something is true', 'He conceded that the plan had flaws.', 4, 'verb'),
('concurrent', '동시의', 'Happening at the same time', 'There were concurrent events at the venue.', 4, 'adjective'),
('constrain', '제약하다', 'To limit or restrict', 'Budget constraints affect the project.', 4, 'verb'),
('context', '맥락', 'The surrounding circumstances', 'Understand the cultural context.', 4, 'noun'),
('contradict', '모순되다', 'To say the opposite of something', 'His actions contradict his words.', 4, 'verb'),
('convey', '전달하다', 'To communicate a message', 'Use simple words to convey your meaning.', 4, 'verb'),
('correlation', '상관관계', 'A connection between two things', 'There is a strong correlation between sleep and health.', 4, 'noun'),
('credibility', '신뢰성', 'The quality of being trusted', 'The report''s credibility was questioned.', 4, 'noun'),
('criterion', '기준', 'A standard used to judge something', 'What criteria do you use to evaluate?', 4, 'noun'),
('crucial', '핵심적인', 'Decisive or critical', 'This step is crucial for the outcome.', 4, 'adjective'),
('cumulative', '누적적인', 'Increasing by repeated additions', 'The cumulative effect is significant.', 4, 'adjective'),
('deduce', '추론하다', 'To reach a conclusion by reasoning', 'Can you deduce the answer from the clues?', 4, 'verb'),
('defer', '미루다', 'To put off until a later time', 'We defer to the expert''s judgment.', 4, 'verb'),
('deliberate', '의도적인', 'Done on purpose or carefully considered', 'It was a deliberate choice.', 4, 'adjective'),
('derive', '도출하다', 'To obtain from a source', 'We derive satisfaction from helping others.', 4, 'verb'),
('designate', '지정하다', 'To officially choose for a purpose', 'She was designated as team leader.', 4, 'verb'),
('deteriorate', '악화되다', 'To become worse', 'The patient''s condition deteriorated.', 4, 'verb'),
('deviate', '일탈하다', 'To differ from a standard', 'Do not deviate from the plan.', 4, 'verb'),
('dilemma', '딜레마', 'A difficult choice between two options', 'He faced a moral dilemma.', 4, 'noun'),
('discrepancy', '불일치', 'A difference between two things', 'There is a discrepancy in the figures.', 4, 'noun'),
('disparity', '불평등', 'A great difference or inequality', 'Income disparity is a growing problem.', 4, 'noun'),
('dominant', '지배적인', 'Most powerful or important', 'English is the dominant language in business.', 4, 'adjective'),
('elaborate', '정교한', 'Having many carefully arranged parts', 'She gave an elaborate explanation.', 4, 'adjective'),
('eliminate', '제거하다', 'To remove completely', 'We must eliminate unnecessary steps.', 4, 'verb'),
('empirical', '경험적인', 'Based on observation and evidence', 'We need empirical data to confirm this.', 4, 'adjective'),
('enhance', '향상시키다', 'To improve the quality of something', 'Good sleep enhances cognitive performance.', 4, 'verb'),
('essentially', '본질적으로', 'In the most important way', 'The two approaches are essentially the same.', 4, 'adverb'),
('evolve', '진화하다', 'To change and develop gradually', 'Language evolves over time.', 4, 'verb'),
('explicit', '명시적인', 'Stated clearly and directly', 'Give explicit instructions.', 4, 'adjective'),
('facilitate', '촉진하다', 'To make something easier', 'Good tools facilitate learning.', 4, 'verb'),
('formulate', '공식화하다', 'To create or prepare carefully', 'Formulate a clear strategy.', 4, 'verb'),
('foundation', '기초', 'A basic principle or system', 'Trust is the foundation of teamwork.', 4, 'noun'),
('framework', '틀', 'A structure for understanding something', 'Use this framework for decision-making.', 4, 'noun'),
('fundamental', '근본적인', 'Basic and important', 'This is a fundamental principle.', 4, 'adjective'),
('generate', '생성하다', 'To produce or create something', 'The engine generates electricity.', 4, 'verb'),
('hypothesis', '가설', 'An idea to be tested by evidence', 'Formulate a hypothesis before the experiment.', 4, 'noun'),
('implicit', '암묵적인', 'Suggested but not directly stated', 'There is an implicit agreement.', 4, 'adjective'),
('inclined', '경향이 있는', 'Having a tendency to do something', 'She is inclined to agree.', 4, 'adjective'),
('incorporate', '통합하다', 'To include something as part of a whole', 'Incorporate feedback into the next version.', 4, 'verb'),
('infer', '추론하다', 'To conclude from evidence', 'We can infer the trend from the data.', 4, 'verb'),
('inherent', '고유한', 'Existing as a natural part', 'There is an inherent risk in the plan.', 4, 'adjective'),
('innovate', '혁신하다', 'To introduce new methods or ideas', 'We must constantly innovate.', 4, 'verb'),
('integral', '필수적인', 'Essential or central to something', 'Feedback is integral to improvement.', 4, 'adjective'),
('integrity', '청렴함', 'The quality of being honest and fair', 'Act with integrity at all times.', 4, 'noun'),
('interpret', '해석하다', 'To explain the meaning of something', 'Interpret the data carefully.', 4, 'verb'),
('intervene', '개입하다', 'To become involved in a situation', 'The manager had to intervene.', 4, 'verb'),
('intuitive', '직관적인', 'Easy to use or understand naturally', 'The interface is intuitive.', 4, 'adjective'),
('leverage', '활용하다', 'To use something to maximum advantage', 'Leverage your strengths in negotiations.', 4, 'verb'),
('manifest', '나타내다', 'To show clearly or become evident', 'Stress can manifest as physical symptoms.', 4, 'verb'),
('marginal', '미미한', 'Relating to the edge or a small amount', 'The improvement was marginal.', 4, 'adjective'),
('mechanism', '메커니즘', 'A system or process for achieving something', 'We need a feedback mechanism.', 4, 'noun'),
('methodology', '방법론', 'A system of methods used in a field', 'Explain your research methodology.', 4, 'noun'),
('minimize', '최소화하다', 'To reduce to the smallest possible amount', 'Minimize waste wherever possible.', 4, 'verb'),
('mutual', '상호의', 'Shared by two people or groups', 'This requires mutual trust and respect.', 4, 'adjective'),
('notion', '개념', 'An idea or belief', 'The notion that hard work pays off.', 4, 'noun'),
('nuance', '뉘앙스', 'A subtle difference in meaning', 'You need to understand the cultural nuance.', 4, 'noun'),
('objective', '객관적인', 'Not influenced by personal feelings', 'Give an objective assessment.', 4, 'adjective'),
('obligation', '의무', 'Something you must do by law or duty', 'We have an obligation to our customers.', 4, 'noun'),
('overlook', '간과하다', 'To fail to notice something', 'Don''t overlook the small details.', 4, 'verb'),
('paradigm', '패러다임', 'A typical example or model', 'This is a paradigm shift in the industry.', 4, 'noun'),
('perceive', '인식하다', 'To become aware of something', 'How do customers perceive the brand?', 4, 'verb'),
('persist', '지속하다', 'To continue despite difficulties', 'If you persist, you will succeed.', 4, 'verb'),
('pragmatic', '실용적인', 'Dealing with things in a practical way', 'Take a pragmatic approach.', 4, 'adjective'),
('predominantly', '주로', 'Mainly, in the greatest number', 'The audience was predominantly young.', 4, 'adverb'),
('preliminary', '예비적인', 'Coming before the main thing', 'Conduct a preliminary review first.', 4, 'adjective'),
('prevalent', '널리 퍼진', 'Widespread at a particular time', 'Misinformation is prevalent online.', 4, 'adjective'),
('principle', '원칙', 'A fundamental truth or law', 'Act according to ethical principles.', 4, 'noun'),

-- ── difficulty 5 (C1~C2 고급 원어민 수준) ──
('abate', '약화되다', 'To become less intense or severe', 'The storm gradually abated.', 5, 'verb'),
('aberrant', '일탈적인', 'Departing from normal behaviour', 'The aberrant data point was excluded.', 5, 'adjective'),
('abrogate', '폐지하다', 'To formally repeal a law or agreement', 'The treaty was abrogated.', 5, 'verb'),
('acumen', '통찰력', 'The ability to judge quickly and well', 'She showed remarkable business acumen.', 5, 'noun'),
('admonish', '훈계하다', 'To warn or caution someone firmly', 'The judge admonished the witness.', 5, 'verb'),
('ambivalent', '양면성의', 'Having mixed feelings about something', 'He felt ambivalent about the promotion.', 5, 'adjective'),
('ameliorate', '개선하다', 'To make a bad situation better', 'Measures were taken to ameliorate the situation.', 5, 'verb'),
('anachronism', '시대착오', 'Something out of its proper time', 'Fax machines are an anachronism.', 5, 'noun'),
('anomaly', '변칙', 'Something that deviates from the standard', 'The anomaly in the data was unexplained.', 5, 'noun'),
('antipathy', '반감', 'A strong feeling of dislike', 'She felt a deep antipathy toward dishonesty.', 5, 'noun'),
('arcane', '비밀스러운', 'Known or understood by very few', 'The arcane rules confused newcomers.', 5, 'adjective'),
('arduous', '힘든', 'Involving great effort or difficulty', 'The climb was arduous but rewarding.', 5, 'adjective'),
('articulate', '명확한', 'Expressing thoughts fluently', 'She is the most articulate speaker.', 5, 'adjective'),
('assiduous', '근면한', 'Showing great care and effort', 'His assiduous study paid off.', 5, 'adjective'),
('astute', '영리한', 'Very perceptive and clever', 'An astute investor spotted the trend early.', 5, 'adjective'),
('atrophy', '위축되다', 'To waste away from lack of use', 'Skills atrophy if not practised.', 5, 'verb'),
('audacious', '대담한', 'Showing willingness to take risks', 'It was an audacious business move.', 5, 'adjective'),
('auspicious', '길조의', 'Indicating a promising future', 'It was an auspicious start to the year.', 5, 'adjective'),
('axiom', '공리', 'A statement accepted as true', 'It is an axiom that honesty builds trust.', 5, 'noun'),
('beguile', '매혹하다', 'To charm or trick cleverly', 'She was beguiled by the salesman''s pitch.', 5, 'verb'),
('belligerent', '호전적인', 'Hostile and aggressive', 'The belligerent tone escalated the conflict.', 5, 'adjective'),
('benevolent', '자비로운', 'Kind and generous', 'A benevolent leader cares for the team.', 5, 'adjective'),
('byzantine', '복잡한', 'Excessively complicated', 'The regulations are byzantine in their complexity.', 5, 'adjective'),
('cacophony', '불협화음', 'A harsh mixture of loud sounds', 'The city street was a cacophony of noise.', 5, 'noun'),
('capricious', '변덕스러운', 'Given to sudden changes of mood', 'The capricious boss changed plans daily.', 5, 'adjective'),
('catalyze', '촉진하다', 'To cause an event to happen faster', 'The crisis catalyzed major reform.', 5, 'verb'),
('caustic', '신랄한', 'Sarcastic or severely critical', 'His caustic remarks offended everyone.', 5, 'adjective'),
('circumvent', '우회하다', 'To find a way around an obstacle', 'He tried to circumvent the regulations.', 5, 'verb'),
('cogent', '설득력 있는', 'Clear and persuasive', 'She made a cogent argument.', 5, 'adjective'),
('complacent', '안주하는', 'Too satisfied with oneself', 'Don''t become complacent after early success.', 5, 'adjective'),
('confound', '혼동시키다', 'To surprise and confuse', 'The results confounded the experts.', 5, 'verb'),
('convoluted', '복잡한', 'Extremely complicated and difficult', 'The explanation was unnecessarily convoluted.', 5, 'adjective'),
('corroborate', '뒷받침하다', 'To confirm or support with evidence', 'Witnesses corroborated the story.', 5, 'verb'),
('counterintuitive', '직관에 반하는', 'Contrary to what you would expect', 'The result was counterintuitive.', 5, 'adjective'),
('credulous', '속기 쉬운', 'Too ready to believe things', 'A credulous person is easy to deceive.', 5, 'adjective'),
('dearth', '부족', 'A scarcity or lack of something', 'There is a dearth of qualified candidates.', 5, 'noun'),
('deference', '존중', 'Respectful submission to another', 'She showed deference to the senior partner.', 5, 'noun'),
('deleterious', '유해한', 'Causing harm or damage', 'Smoking has a deleterious effect on health.', 5, 'adjective'),
('delineate', '묘사하다', 'To describe or indicate precisely', 'Delineate the project boundaries clearly.', 5, 'verb'),
('denounce', '비난하다', 'To publicly criticize or condemn', 'The senator denounced the policy.', 5, 'verb'),
('deprecate', '반대하다', 'To express disapproval of something', 'The feature was deprecated in the update.', 5, 'verb'),
('derogatory', '경멸적인', 'Expressing a low opinion', 'Avoid derogatory language in the workplace.', 5, 'adjective'),
('diffuse', '분산시키다', 'To spread over a wide area', 'Good lighting diffuses evenly.', 5, 'verb'),
('diminish', '줄어들다', 'To make or become smaller', 'The pain will diminish over time.', 5, 'verb'),
('discern', '식별하다', 'To recognize or perceive clearly', 'It is hard to discern the truth.', 5, 'verb'),
('dispel', '없애다', 'To make a feeling or belief disappear', 'Facts dispel myths and misconceptions.', 5, 'verb'),
('dissonance', '불협화음', 'A tension from conflicting elements', 'Cognitive dissonance causes discomfort.', 5, 'noun'),
('dogmatic', '독단적인', 'Laying down principles as absolute', 'A dogmatic leader refuses all feedback.', 5, 'adjective'),
('dubious', '의심스러운', 'Doubtful or uncertain', 'I am dubious about the plan''s success.', 5, 'adjective'),
('ebullient', '넘치는 활기의', 'Cheerful and full of energy', 'She had an ebullient personality.', 5, 'adjective'),
('eclectic', '절충적인', 'Taking from a variety of sources', 'Her taste in music is eclectic.', 5, 'adjective'),
('efficacious', '효과적인', 'Producing the desired result', 'The new drug is highly efficacious.', 5, 'adjective'),
('elusive', '파악하기 어려운', 'Difficult to find or achieve', 'Success can be elusive.', 5, 'adjective'),
('emulate', '모방하다', 'To match or surpass by imitation', 'Emulate the best practices of leaders.', 5, 'verb'),
('endemic', '풍토병의', 'Regularly found in a particular place', 'Corruption is endemic in the system.', 5, 'adjective'),
('ephemeral', '덧없는', 'Lasting for only a short time', 'Fame is often ephemeral.', 5, 'adjective'),
('equivocate', '모호하게 말하다', 'To use ambiguous language to avoid truth', 'Stop equivocating and give a clear answer.', 5, 'verb'),
('erudite', '학식 있는', 'Having or showing great knowledge', 'He is an erudite scholar.', 5, 'adjective'),
('esoteric', '난해한', 'Understood by only a few people', 'The lecture was too esoteric for beginners.', 5, 'adjective'),
('exacerbate', '악화시키다', 'To make a problem worse', 'Stress can exacerbate health problems.', 5, 'verb'),
('exemplary', '모범적인', 'Serving as a desirable model', 'Her work was exemplary.', 5, 'adjective'),
('expedient', '편의주의적인', 'Convenient and useful in a given situation', 'The decision was expedient but not ideal.', 5, 'adjective'),
('extraneous', '관계없는', 'Irrelevant or unrelated to the matter', 'Remove extraneous information from the report.', 5, 'adjective'),
('fallacious', '잘못된', 'Based on an error in reasoning', 'That is a fallacious argument.', 5, 'adjective'),
('fastidious', '까다로운', 'Very attentive to detail', 'She is fastidious about punctuation.', 5, 'adjective'),
('fervent', '열렬한', 'Having or showing great passion', 'He is a fervent supporter of the cause.', 5, 'adjective'),
('flagrant', '명백한', 'Obviously offensive or bad', 'It was a flagrant violation of the rules.', 5, 'adjective'),
('fleeting', '잠깐의', 'Lasting for a very short time', 'I had a fleeting glimpse of the bird.', 5, 'adjective'),
('frugal', '검소한', 'Careful with money and resources', 'A frugal lifestyle helps save money.', 5, 'adjective'),
('futile', '헛된', 'Having no purpose or effect', 'Further argument was futile.', 5, 'adjective'),
('garrulous', '수다스러운', 'Excessively talkative', 'The garrulous neighbour never stops talking.', 5, 'adjective'),
('grandiose', '과대한', 'Impressive or ambitious in scale', 'The grandiose plans were never realized.', 5, 'adjective'),
('gregarious', '사교적인', 'Fond of company and social interaction', 'He is a gregarious person who loves parties.', 5, 'adjective'),
('hackneyed', '진부한', 'Used so often as to be meaningless', 'Avoid hackneyed phrases in writing.', 5, 'adjective'),
('harangue', '호통치다', 'To lecture or scold at length', 'He harangued the team for their poor performance.', 5, 'verb'),
('hegemony', '패권', 'Leadership or dominance', 'The company maintained market hegemony.', 5, 'noun'),
('heretical', '이단의', 'Opposed to accepted belief', 'His ideas were considered heretical.', 5, 'adjective'),
('hypocritical', '위선적인', 'Behaving contrary to stated beliefs', 'It is hypocritical to say one thing and do another.', 5, 'adjective'),
('idiosyncratic', '독특한', 'Relating to unusual individual characteristics', 'Her idiosyncratic style stood out.', 5, 'adjective'),
('immutable', '불변의', 'Unchangeable or permanent', 'Some natural laws are immutable.', 5, 'adjective'),
('imperious', '거만한', 'Arrogantly domineering', 'His imperious manner alienated colleagues.', 5, 'adjective'),
('impetuous', '충동적인', 'Acting without thought', 'An impetuous decision can cause problems.', 5, 'adjective'),
('impudent', '뻔뻔한', 'Not showing due respect', 'The impudent remark shocked everyone.', 5, 'adjective'),
('incisive', '날카로운', 'Intelligently sharp and clear', 'She made an incisive observation.', 5, 'adjective'),
('incontrovertible', '반박할 수 없는', 'Not able to be denied', 'The evidence was incontrovertible.', 5, 'adjective'),
('indolent', '게으른', 'Wanting to avoid activity', 'An indolent worker drags the team down.', 5, 'adjective'),
('inexorable', '막을 수 없는', 'Impossible to stop or prevent', 'The inexorable march of technology continues.', 5, 'adjective'),
('insidious', '교활한', 'Proceeding in a harmful but gradual way', 'Burnout can be insidious.', 5, 'adjective'),
('intransigent', '타협하지 않는', 'Refusing to change one''s position', 'The intransigent negotiator blocked progress.', 5, 'adjective'),
('inveterate', '오래된', 'Having a habit difficult to change', 'He is an inveterate optimist.', 5, 'adjective'),
('irascible', '성급한', 'Easily made angry', 'The irascible professor scared students.', 5, 'adjective'),
('laconic', '간결한', 'Using very few words', 'He gave a laconic reply: ''No''.', 5, 'adjective'),
('loquacious', '수다스러운', 'Talking a great deal', 'A loquacious speaker can lose the audience.', 5, 'adjective'),
('magnanimous', '관대한', 'Very generous or forgiving', 'The magnanimous leader praised the team.', 5, 'adjective'),
('malleable', '유연한', 'Easily changed or influenced', 'Young minds are malleable and open.', 5, 'adjective'),
('mendacious', '거짓말하는', 'Not telling the truth', 'The mendacious report misled investors.', 5, 'adjective'),
('mercurial', '변덕스러운', 'Subject to sudden changes of mood', 'Her mercurial temper made management hard.', 5, 'adjective'),
('meticulous', '꼼꼼한', 'Extremely careful and precise', 'A meticulous plan leaves nothing to chance.', 5, 'adjective'),
('mitigate', '완화하다', 'To reduce the severity of something', 'Steps were taken to mitigate the risk.', 5, 'verb'),
('mundane', '평범한', 'Ordinary, lacking excitement', 'The work was mundane but necessary.', 5, 'adjective'),
('nebulous', '모호한', 'Not clear or defined', 'His goals were nebulous and hard to measure.', 5, 'adjective'),
('nefarious', '사악한', 'Wicked or criminal', 'The nefarious scheme was uncovered.', 5, 'adjective')

ON CONFLICT (word) DO NOTHING;
