-- v1.7: words 배치2 — 456개 추가 (목표 2,000개)
-- 범주: phrasal verbs, 직장·일상 명사, 형용사, 표현

INSERT INTO words (word, definition_ko, definition_en, example_sentence, difficulty, category)
VALUES

-- ── difficulty 1 (A1 기초) ──
('address', '주소', 'The location where a person lives or works', 'Please write your address on this form.', 1, 'noun'),
('age', '나이', 'The number of years someone has lived', 'What is your age?', 1, 'noun'),
('bank', '은행', 'A place where people keep money', 'I need to go to the bank today.', 1, 'noun'),
('body', '몸', 'The physical structure of a person or animal', 'Exercise is good for the body.', 1, 'noun'),
('boy', '소년', 'A male child', 'The boy is playing in the park.', 1, 'noun'),
('bread', '빵', 'A baked food made from flour', 'She bought a loaf of bread.', 1, 'noun'),
('city', '도시', 'A large town with many people', 'Tokyo is a very big city.', 1, 'noun'),
('class', '수업', 'A group lesson or educational session', 'I have an English class at 9 a.m.', 1, 'noun'),
('color', '색깔', 'A visual property like red or blue', 'What is your favorite color?', 1, 'noun'),
('company', '회사', 'A business organization', 'She works for a big company.', 1, 'noun'),
('country', '나라', 'A nation with its own government', 'Korea is a beautiful country.', 1, 'noun'),
('data', '데이터', 'Facts and information collected together', 'We need more data to decide.', 1, 'noun'),
('date', '날짜', 'A specific day in the calendar', 'What is today''s date?', 1, 'noun'),
('email', '이메일', 'A message sent electronically', 'I will send you an email.', 1, 'noun'),
('girl', '소녀', 'A female child', 'The girl smiled at her teacher.', 1, 'noun'),
('job', '직업', 'Work that someone does to earn money', 'He got a new job last week.', 1, 'noun'),
('man', '남자', 'An adult male person', 'A man walked into the store.', 1, 'noun'),
('meeting', '회의', 'A gathering of people to discuss something', 'The meeting starts at 10 a.m.', 1, 'noun'),
('money', '돈', 'Coins or notes used to buy things', 'I don''t have enough money.', 1, 'noun'),
('number', '숫자', 'A word or symbol representing quantity', 'Write your phone number here.', 1, 'noun'),
('office', '사무실', 'A room or building for work', 'She arrived at the office early.', 1, 'noun'),
('park', '공원', 'A public area with grass and trees', 'We walked in the park after lunch.', 1, 'noun'),
('party', '파티', 'A social gathering for celebration', 'They threw a party for her birthday.', 1, 'noun'),
('place', '장소', 'A particular area or location', 'This is a nice place to sit.', 1, 'noun'),
('plan', '계획', 'An idea about how to do something', 'What is your plan for the weekend?', 1, 'noun'),
('price', '가격', 'The amount of money for something', 'The price of coffee went up.', 1, 'noun'),
('restaurant', '식당', 'A place where you can eat meals', 'Let''s go to that new restaurant.', 1, 'noun'),
('shop', '가게', 'A place where goods are sold', 'The shop closes at 9 p.m.', 1, 'noun'),
('song', '노래', 'A piece of music with words', 'She sang a beautiful song.', 1, 'noun'),
('store', '상점', 'A place that sells goods', 'I went to the store to buy milk.', 1, 'noun'),
('student', '학생', 'A person who studies at school', 'Every student did the homework.', 1, 'noun'),
('town', '마을', 'A place smaller than a city', 'She grew up in a small town.', 1, 'noun'),
('week', '주', 'A period of seven days', 'I will see you next week.', 1, 'noun'),
('woman', '여자', 'An adult female person', 'A woman opened the door.', 1, 'noun'),
('year', '해', 'A period of 12 months', 'I moved here last year.', 1, 'noun'),

-- ── difficulty 2 (A2 초급) ──
('achievement', '성취', 'Something accomplished through effort', 'Finishing the marathon was a great achievement.', 2, 'noun'),
('activity', '활동', 'Something that you do', 'Swimming is a healthy activity.', 2, 'noun'),
('agree', '동의하다', 'To have the same opinion as someone', 'I agree with your point.', 2, 'verb'),
('already', '이미', 'Before the time expected', 'She has already finished the work.', 2, 'adverb'),
('angry', '화난', 'Feeling strong annoyance or displeasure', 'He was angry about the mistake.', 2, 'adjective'),
('apologize', '사과하다', 'To say you are sorry', 'I want to apologize for being late.', 2, 'verb'),
('article', '기사', 'A piece of writing in a newspaper or magazine', 'I read an interesting article today.', 2, 'noun'),
('borrow', '빌리다', 'To take something with permission to return it', 'Can I borrow your pen?', 2, 'verb'),
('break down', '고장나다', 'To stop working or fail suddenly', 'My car broke down on the highway.', 2, 'phrase'),
('budget', '예산', 'A plan for how to spend money', 'We need to stay within budget.', 2, 'noun'),
('building', '건물', 'A structure with walls and a roof', 'The office is in a tall building.', 2, 'noun'),
('busy', '바쁜', 'Having a lot of things to do', 'I am very busy this week.', 2, 'adjective'),
('call back', '다시 전화하다', 'To telephone someone in return', 'I will call you back in five minutes.', 2, 'phrase'),
('career', '경력', 'A long-term professional path', 'She has had a successful career in design.', 2, 'noun'),
('cash', '현금', 'Physical money as coins and banknotes', 'Do you pay by cash or card?', 2, 'noun'),
('catch up', '따라잡다', 'To reach the same level as others', 'I need to catch up on my emails.', 2, 'phrase'),
('charge', '청구하다', 'To ask someone to pay a price', 'How much do they charge for parking?', 2, 'verb'),
('clear', '명확한', 'Easy to understand or see', 'Please give a clear explanation.', 2, 'adjective'),
('client', '고객', 'A person who pays for services', 'We have a new client meeting.', 2, 'noun'),
('close', '닫다', 'To move something to cover an opening', 'Please close the window.', 2, 'verb'),
('comment', '댓글', 'A remark or opinion expressed', 'She left a comment on my post.', 2, 'noun'),
('competition', '경쟁', 'A situation where people try to win', 'The competition was very tough.', 2, 'noun'),
('complain', '불평하다', 'To express dissatisfaction', 'He complained about the noise.', 2, 'verb'),
('convenient', '편리한', 'Easy to do or use', 'The store location is very convenient.', 2, 'adjective'),
('cost', '비용', 'The amount paid for something', 'The cost of living is high here.', 2, 'noun'),
('creative', '창의적인', 'Able to produce new and original ideas', 'She is a very creative designer.', 2, 'adjective'),
('deal with', '처리하다', 'To take action to handle something', 'How do you deal with stress?', 2, 'phrase'),
('deadline', '마감일', 'The latest time something must be done', 'The deadline is Friday at 5 p.m.', 2, 'noun'),
('decline', '거절하다', 'To politely say no to something', 'She declined the job offer.', 2, 'verb'),
('department', '부서', 'A section of an organization', 'I work in the marketing department.', 2, 'noun'),
('draw up', '작성하다', 'To prepare a written document', 'Can you draw up a contract?', 2, 'phrase'),
('driver', '운전기사', 'A person who drives a vehicle', 'The driver was very friendly.', 2, 'noun'),
('early', '이른', 'Before the usual or expected time', 'She always arrives early to work.', 2, 'adjective'),
('easy', '쉬운', 'Not requiring much effort', 'This test was easy.', 2, 'adjective'),
('employee', '직원', 'A person who works for an employer', 'All employees must sign in.', 2, 'noun'),
('employer', '고용주', 'A person or company that hires workers', 'My employer pays me every month.', 2, 'noun'),
('end up', '결국 ~하게 되다', 'To finally be in a situation or place', 'We ended up going to the cinema.', 2, 'phrase'),
('envelope', '봉투', 'A flat paper container for letters', 'Put the letter in the envelope.', 2, 'noun'),
('fall behind', '뒤처지다', 'To fail to keep up with others', 'Don''t fall behind on your work.', 2, 'phrase'),
('feedback', '피드백', 'Opinions about something to help improve it', 'Can you give me feedback on my report?', 2, 'noun'),
('file', '파일', 'A collection of data or documents', 'Please save the file before closing.', 2, 'noun'),
('fill up', '가득 채우다', 'To make something completely full', 'Fill up the tank before the trip.', 2, 'phrase'),
('fit in', '어울리다', 'To belong or feel comfortable in a group', 'He quickly fit in with the team.', 2, 'phrase'),
('full', '가득 찬', 'Containing as much as possible', 'The bus is full.', 2, 'adjective'),
('get over', '극복하다', 'To recover from or stop being upset', 'It takes time to get over a loss.', 2, 'phrase'),
('get rid of', '제거하다', 'To remove or dispose of something', 'I need to get rid of old clothes.', 2, 'phrase'),
('give up', '포기하다', 'To stop trying to do something', 'Never give up on your dreams.', 2, 'phrase'),
('go ahead', '진행하다', 'To proceed or continue with something', 'Go ahead and start the meeting.', 2, 'phrase'),
('go over', '검토하다', 'To review or examine something carefully', 'Let''s go over the plan one more time.', 2, 'phrase'),
('grow up', '자라다', 'To develop from a child into an adult', 'She grew up in Seoul.', 2, 'phrase'),
('hand in', '제출하다', 'To give something to someone in authority', 'Please hand in your homework by Friday.', 2, 'phrase'),
('hand out', '나눠주다', 'To distribute to a group of people', 'The teacher handed out worksheets.', 2, 'phrase'),
('handle', '다루다', 'To deal with a situation or task', 'She can handle any problem calmly.', 2, 'verb'),
('helpful', '도움이 되는', 'Making things easier or better', 'The staff was very helpful.', 2, 'adjective'),
('honest', '정직한', 'Telling the truth and being sincere', 'Please be honest with me.', 2, 'adjective'),
('hospital', '병원', 'A place where people receive medical care', 'She was taken to the hospital.', 2, 'noun'),
('household', '가정', 'All the people living together in a house', 'Every household has different needs.', 2, 'noun'),
('huge', '거대한', 'Very large in size', 'They live in a huge house.', 2, 'adjective'),
('identity', '정체성', 'Who a person is', 'Personal identity is important.', 2, 'noun'),
('internet', '인터넷', 'A global network of computers', 'I use the internet every day.', 2, 'noun'),
('invoice', '청구서', 'A list of goods with prices sent to a buyer', 'Please send the invoice by email.', 2, 'noun'),
('join', '참가하다', 'To become a member of a group', 'I want to join the gym.', 2, 'verb'),
('keep up', '유지하다', 'To continue at the same level or pace', 'It''s hard to keep up with the news.', 2, 'phrase'),
('kick off', '시작하다', 'To begin or start something', 'Let''s kick off the project tomorrow.', 2, 'phrase'),
('label', '라벨', 'A small piece of paper giving information', 'Check the label before washing.', 2, 'noun'),
('late', '늦은', 'After the expected time', 'Sorry, I''m late for the meeting.', 2, 'adjective'),
('leader', '지도자', 'A person who guides others', 'She is a natural leader.', 2, 'noun'),
('leave out', '빼다', 'To not include something', 'You can leave out the dessert.', 2, 'phrase'),
('let down', '실망시키다', 'To disappoint someone', 'Don''t let your team down.', 2, 'phrase'),
('license', '면허증', 'An official permission to do something', 'Do you have a driver''s license?', 2, 'noun'),
('list', '목록', 'A series of items written one after another', 'Make a shopping list before going.', 2, 'noun'),
('location', '위치', 'A particular place or position', 'The office location is ideal.', 2, 'noun'),
('look up', '찾아보다', 'To search for information', 'Look up the word in the dictionary.', 2, 'phrase'),
('magazine', '잡지', 'A publication with articles and pictures', 'I read a cooking magazine.', 2, 'noun'),
('make sure', '확인하다', 'To check that something is done correctly', 'Make sure you lock the door.', 2, 'phrase'),
('mention', '언급하다', 'To refer to something briefly', 'Did you mention the deadline?', 2, 'verb'),
('move on', '앞으로 나아가다', 'To go forward after something has ended', 'It''s time to move on.', 2, 'phrase'),
('narrow down', '좁히다', 'To reduce the number of choices', 'Let''s narrow down the options.', 2, 'phrase'),
('neighborhood', '동네', 'The area where someone lives', 'It''s a quiet neighborhood.', 2, 'noun'),
('object', '물체', 'A physical thing that can be touched', 'What is this round object?', 2, 'noun'),
('order', '주문', 'A request for something to be made or delivered', 'Can I take your order?', 2, 'noun'),
('organize', '정리하다', 'To arrange things in a structured way', 'I need to organize my desk.', 2, 'verb'),
('overtime', '초과근무', 'Time worked beyond regular hours', 'He worked overtime to finish the project.', 2, 'noun'),
('package', '소포', 'A parcel wrapped for delivery', 'A package arrived for you.', 2, 'noun'),
('partner', '파트너', 'A person who shares in an activity', 'She is my business partner.', 2, 'noun'),
('path', '경로', 'A way or route from one place to another', 'Take the path through the park.', 2, 'noun'),
('pay off', '갚다', 'To pay a debt in full', 'I finally paid off my student loan.', 2, 'phrase'),
('performance', '성과', 'How well someone does something', 'Her performance at work was excellent.', 2, 'noun'),
('personality', '성격', 'The qualities that make a person unique', 'She has a warm personality.', 2, 'noun'),
('pick up', '픽업하다', 'To collect or take someone or something', 'Can you pick me up at 7?', 2, 'phrase'),
('platform', '플랫폼', 'A raised surface or digital environment', 'We use Slack as our main platform.', 2, 'noun'),
('polite', '예의바른', 'Behaving in a respectful and courteous way', 'Be polite to your customers.', 2, 'adjective'),
('product', '제품', 'Something made to be sold', 'This product sells very well.', 2, 'noun'),
('proposal', '제안서', 'A plan or offer put forward for consideration', 'They sent a detailed proposal.', 2, 'noun'),
('put off', '미루다', 'To delay or postpone something', 'Don''t put off important tasks.', 2, 'phrase'),
('reach out', '연락하다', 'To make contact with someone', 'Feel free to reach out if you need help.', 2, 'phrase'),
('recipe', '레시피', 'Instructions for preparing food', 'Can you share the recipe?', 2, 'noun'),
('record', '기록', 'Written information kept for future use', 'Keep a record of all expenses.', 2, 'noun'),
('register', '등록하다', 'To officially sign up or enroll', 'Please register for the event online.', 2, 'verb'),
('request', '요청', 'An act of asking for something', 'I made a request for a day off.', 2, 'noun'),
('review', '검토', 'A critical evaluation or examination', 'Let''s do a quick review of the plan.', 2, 'noun'),
('rule out', '배제하다', 'To decide something is impossible', 'We can rule out that option.', 2, 'phrase'),
('salary', '급여', 'A fixed regular payment for work', 'Her salary increased this year.', 2, 'noun'),
('section', '섹션', 'A distinct part of something larger', 'Read the last section of the report.', 2, 'noun'),
('select', '선택하다', 'To carefully choose from a range of options', 'Select your preferred language.', 2, 'verb'),
('show up', '나타나다', 'To arrive or appear somewhere', 'He didn''t show up for the meeting.', 2, 'phrase'),
('sign up', '등록하다', 'To register for something officially', 'Sign up for the free trial.', 2, 'phrase'),
('slow down', '속도를 줄이다', 'To reduce speed or pace', 'You need to slow down and relax.', 2, 'phrase'),
('sort out', '해결하다', 'To resolve or organize something', 'Let''s sort out this issue today.', 2, 'phrase'),
('speak up', '크게 말하다', 'To say something more loudly or clearly', 'Please speak up so everyone can hear.', 2, 'phrase'),
('staff', '직원', 'The employees of an organization', 'The staff meeting is at noon.', 2, 'noun'),
('stand out', '눈에 띄다', 'To be clearly better or more noticeable', 'Her work always stands out.', 2, 'phrase'),
('statement', '성명', 'A formal declaration or announcement', 'The CEO made a statement.', 2, 'noun'),
('status', '상태', 'The current condition or situation', 'What is the status of the project?', 2, 'noun'),
('step up', '강화하다', 'To increase effort or take on more responsibility', 'We need to step up our game.', 2, 'phrase'),
('submit', '제출하다', 'To formally hand in for review', 'Submit the form by Monday.', 2, 'verb'),
('supply', '공급하다', 'To provide what is needed', 'We supply products to retailers.', 2, 'verb'),
('target', '목표', 'An objective or aim to achieve', 'We hit our sales target this month.', 2, 'noun'),
('think over', '심사숙고하다', 'To consider something carefully', 'Take time to think over the offer.', 2, 'phrase'),
('topic', '주제', 'A subject of discussion', 'The topic of today''s meeting is sales.', 2, 'noun'),
('track down', '추적하다', 'To find something or someone by searching', 'I finally tracked down the information.', 2, 'phrase'),
('training', '교육', 'The process of learning skills', 'New employees receive training.', 2, 'noun'),
('turn down', '거절하다', 'To reject an offer or request', 'She turned down the promotion.', 2, 'phrase'),
('turn up', '나타나다', 'To arrive unexpectedly', 'He turned up without any warning.', 2, 'phrase'),
('update', '업데이트', 'New information or a newer version', 'I sent you an update on the project.', 2, 'noun'),
('version', '버전', 'A form of something that differs slightly from others', 'Please use the latest version.', 2, 'noun'),
('view', '견해', 'A personal opinion or perspective', 'What is your view on this issue?', 2, 'noun'),
('wind up', '마무리하다', 'To bring to a conclusion', 'Let''s wind up the meeting.', 2, 'phrase'),
('work on', '작업하다', 'To spend time doing something', 'I''m working on a new project.', 2, 'phrase'),
('wrap up', '마무리하다', 'To finish or complete something', 'Let''s wrap up this discussion.', 2, 'phrase'),

-- ── difficulty 3 (B1 중급) ──
('accessible', '접근 가능한', 'Easy to reach, use or understand', 'The information should be accessible to all.', 3, 'adjective'),
('accomplish', '달성하다', 'To successfully achieve something', 'We accomplished all our goals this quarter.', 3, 'verb'),
('account for', '설명하다', 'To give an explanation for something', 'Can you account for the missing funds?', 3, 'phrase'),
('action plan', '행동 계획', 'A set of steps to achieve a goal', 'We need a clear action plan.', 3, 'noun'),
('agenda', '의제', 'A list of items to be discussed', 'Please check the meeting agenda.', 3, 'noun'),
('agreement', '합의', 'An arrangement accepted by all parties', 'We reached an agreement on the price.', 3, 'noun'),
('aid', '돕다', 'To help or support someone', 'Volunteers aided flood victims.', 3, 'verb'),
('alert', '경고', 'A warning about a possible danger', 'The system sent an alert.', 3, 'noun'),
('allocate', '배분하다', 'To give resources to a particular purpose', 'Allocate enough time for review.', 3, 'verb'),
('ambitious', '야심찬', 'Having a strong desire to succeed', 'She set ambitious goals for herself.', 3, 'adjective'),
('analysis', '분석', 'A detailed examination of something', 'The report includes a market analysis.', 3, 'noun'),
('announce', '발표하다', 'To make something publicly known', 'The manager announced the new policy.', 3, 'verb'),
('approve', '승인하다', 'To officially agree or accept', 'The board approved the proposal.', 3, 'verb'),
('arrange', '준비하다', 'To put things in order or plan an event', 'I will arrange a meeting for next week.', 3, 'verb'),
('assignment', '과제', 'A task given to someone', 'Complete the assignment by Friday.', 3, 'noun'),
('assist', '보조하다', 'To help someone do something', 'Can you assist me with this form?', 3, 'verb'),
('at first glance', '처음 보기엔', 'As something appears when seen initially', 'At first glance the plan seems simple.', 3, 'phrase'),
('attract', '끌어들이다', 'To cause someone to come to a place', 'Good design attracts customers.', 3, 'verb'),
('audience', '청중', 'A group of people watching or listening', 'The audience applauded loudly.', 3, 'noun'),
('awareness', '인식', 'Knowledge or understanding of a situation', 'Raise awareness about safety rules.', 3, 'noun'),
('balance out', '균형을 맞추다', 'To make equal by adding or removing', 'The positives balance out the negatives.', 3, 'phrase'),
('benchmark', '기준', 'A standard used for comparison', 'Set a benchmark to measure progress.', 3, 'noun'),
('bonus', '보너스', 'Extra money given as a reward', 'She received a year-end bonus.', 3, 'noun'),
('break up', '해체하다', 'To end a relationship or group', 'The team broke up after the project.', 3, 'phrase'),
('bring up', '언급하다', 'To mention a subject in conversation', 'He brought up an important concern.', 3, 'phrase'),
('bump into', '우연히 마주치다', 'To meet someone unexpectedly', 'I bumped into an old friend.', 3, 'phrase'),
('capable', '유능한', 'Having the ability to do something well', 'She is a very capable manager.', 3, 'adjective'),
('cash flow', '현금흐름', 'The movement of money in and out of a business', 'We need to improve our cash flow.', 3, 'noun'),
('challenge', '도전', 'Something difficult that requires effort', 'Working remotely has its challenges.', 3, 'noun'),
('character', '성격', 'The mental and moral qualities of a person', 'He has a strong character.', 3, 'noun'),
('charity', '자선단체', 'An organization that helps people in need', 'She volunteers at a local charity.', 3, 'noun'),
('check in', '체크인하다', 'To confirm arrival or status with someone', 'Please check in when you arrive.', 3, 'phrase'),
('check out', '확인하다', 'To examine or investigate something', 'Check out the new product features.', 3, 'phrase'),
('commit', '전념하다', 'To dedicate yourself to something', 'Commit to improving every day.', 3, 'verb'),
('competitive', '경쟁적인', 'Relating to or involving competition', 'The job market is very competitive.', 3, 'adjective'),
('confident', '자신감 있는', 'Feeling sure about your own abilities', 'Be confident when presenting.', 3, 'adjective'),
('connection', '연결', 'A relationship or link between things', 'There is a connection between diet and health.', 3, 'noun'),
('consumer', '소비자', 'A person who buys goods or services', 'Consumer demand is rising.', 3, 'noun'),
('consult', '상담하다', 'To seek advice from an expert', 'Please consult a doctor before starting.', 3, 'verb'),
('convert', '전환하다', 'To change into a different form', 'Convert the file to PDF.', 3, 'verb'),
('cooperate', '협력하다', 'To work together toward a shared goal', 'Teams must cooperate to succeed.', 3, 'verb'),
('courage', '용기', 'The ability to do something despite fear', 'It takes courage to speak up.', 3, 'noun'),
('critical', '중요한', 'Of great importance or urgency', 'This is a critical decision.', 3, 'adjective'),
('current', '현재의', 'Happening or existing now', 'What is the current status?', 3, 'adjective'),
('cut back', '줄이다', 'To reduce the amount of something', 'We need to cut back on expenses.', 3, 'phrase'),
('cut off', '차단하다', 'To stop supplying or interrupt something', 'The power was cut off during the storm.', 3, 'phrase'),
('dedicated', '헌신적인', 'Devoted to a task or purpose', 'She is a dedicated worker.', 3, 'adjective'),
('defense', '방어', 'Protection against attack or harm', 'The best defense is preparation.', 3, 'noun'),
('destination', '목적지', 'The place someone is traveling to', 'Seoul is a popular tourist destination.', 3, 'noun'),
('development', '발전', 'The process of growth or progress', 'Professional development is important.', 3, 'noun'),
('diverse', '다양한', 'Including many different types or elements', 'We need a diverse team.', 3, 'adjective'),
('draw up', '기안하다', 'To write or prepare a document formally', 'The lawyer will draw up the agreement.', 3, 'phrase'),
('dress up', '차려입다', 'To wear special or formal clothing', 'Dress up for the presentation.', 3, 'phrase'),
('dynamic', '역동적인', 'Energetic and constantly changing', 'The market is dynamic and fast-moving.', 3, 'adjective'),
('effective', '효과적인', 'Producing the desired result', 'This is an effective strategy.', 3, 'adjective'),
('engagement', '참여', 'Active involvement in something', 'Customer engagement has increased.', 3, 'noun'),
('ensure', '보장하다', 'To make certain something happens', 'Ensure all documents are signed.', 3, 'verb'),
('establish', '설립하다', 'To set up or start something officially', 'The company was established in 2010.', 3, 'verb'),
('evaluate', '평가하다', 'To judge or assess the value of something', 'Evaluate each option before deciding.', 3, 'verb'),
('fair', '공정한', 'Treating everyone equally', 'The decision was fair to everyone.', 3, 'adjective'),
('fall through', '무산되다', 'To fail to happen as planned', 'The deal fell through at the last minute.', 3, 'phrase'),
('fascinating', '매혹적인', 'Extremely interesting or charming', 'The talk was absolutely fascinating.', 3, 'adjective'),
('figure out', '알아내다', 'To understand or solve something', 'Can you figure out what the problem is?', 3, 'phrase'),
('gain', '얻다', 'To obtain or achieve something', 'We gained a lot of experience.', 3, 'verb'),
('genuine', '진정한', 'Truly what it is claimed to be', 'She showed genuine interest.', 3, 'adjective'),
('give in', '굴복하다', 'To stop resisting and agree', 'Don''t give in to pressure.', 3, 'phrase'),
('go back', '돌아가다', 'To return to a place or situation', 'We need to go back to basics.', 3, 'phrase'),
('grateful', '감사하는', 'Feeling thankful for something', 'I am grateful for the opportunity.', 3, 'adjective'),
('guarantee', '보장하다', 'To promise that something will happen', 'We guarantee customer satisfaction.', 3, 'verb'),
('hire', '고용하다', 'To officially employ someone', 'We plan to hire five new employees.', 3, 'verb'),
('hold on', '기다리다', 'To wait for a short time', 'Hold on a moment, please.', 3, 'phrase'),
('hold up', '지연시키다', 'To delay or obstruct progress', 'Traffic held up the delivery.', 3, 'phrase'),
('ignore', '무시하다', 'To pay no attention to something', 'Don''t ignore customer feedback.', 3, 'verb'),
('immediate', '즉각적인', 'Happening without any delay', 'We need an immediate response.', 3, 'adjective'),
('independent', '독립적인', 'Not relying on others', 'She is a very independent thinker.', 3, 'adjective'),
('inspect', '점검하다', 'To look at something carefully to check quality', 'Inspect the product before shipping.', 3, 'verb'),
('intend', '의도하다', 'To plan or mean to do something', 'I intend to finish by end of day.', 3, 'verb'),
('international', '국제적인', 'Involving more than one country', 'We have international clients.', 3, 'adjective'),
('judge', '판단하다', 'To form an opinion about something', 'Don''t judge a book by its cover.', 3, 'verb'),
('lack', '부족하다', 'To not have enough of something', 'They lack the resources to complete it.', 3, 'verb'),
('lay off', '해고하다', 'To dismiss workers due to budget cuts', 'The company laid off 20 employees.', 3, 'phrase'),
('likelihood', '가능성', 'The probability that something will happen', 'What is the likelihood of success?', 3, 'noun'),
('look back', '되돌아보다', 'To think about past events', 'Let''s look back at what we achieved.', 3, 'phrase'),
('make do', '그럭저럭 하다', 'To manage with what is available', 'We''ll have to make do with less.', 3, 'phrase'),
('make out', '이해하다', 'To manage to see or hear something', 'I could barely make out his words.', 3, 'phrase'),
('meaningful', '의미 있는', 'Having real importance or purpose', 'Create meaningful relationships.', 3, 'adjective'),
('motivated', '동기부여된', 'Enthusiastic and determined', 'Employees need to feel motivated.', 3, 'adjective'),
('negotiate', '협상하다', 'To discuss to reach an agreement', 'We negotiated the contract terms.', 3, 'verb'),
('official', '공식적인', 'Relating to an authority or organization', 'Send an official letter.', 3, 'adjective'),
('operate', '운영하다', 'To control or run a system or machine', 'The machine operates automatically.', 3, 'verb'),
('optional', '선택적인', 'Available to be chosen but not required', 'Attendance is optional.', 3, 'adjective'),
('organized', '체계적인', 'Arranged in a structured way', 'She is very organized and efficient.', 3, 'adjective'),
('outstanding', '뛰어난', 'Exceptionally good', 'His work is outstanding.', 3, 'adjective'),
('overcome', '극복하다', 'To succeed in dealing with a problem', 'Overcome obstacles with persistence.', 3, 'verb'),
('pass on', '전달하다', 'To give something to someone else', 'Pass on the message to the team.', 3, 'phrase'),
('permit', '허락하다', 'To officially allow something', 'Photography is not permitted here.', 3, 'verb'),
('pick out', '골라내다', 'To choose or select something specific', 'Pick out the best candidates.', 3, 'phrase'),
('positive', '긍정적인', 'Good, optimistic, or constructive', 'Stay positive despite challenges.', 3, 'adjective'),
('powerful', '강력한', 'Having great strength or influence', 'A powerful message reaches more people.', 3, 'adjective'),
('predict', '예측하다', 'To say what will happen in the future', 'It is hard to predict the market.', 3, 'verb'),
('prefer', '선호하다', 'To like one thing more than another', 'I prefer working in the morning.', 3, 'verb'),
('productive', '생산적인', 'Achieving a lot in an efficient way', 'We had a productive meeting.', 3, 'adjective'),
('professional', '전문적인', 'Relating to a job requiring expertise', 'Keep a professional tone in emails.', 3, 'adjective'),
('propose', '제안하다', 'To put forward an idea or plan', 'I propose we meet next Monday.', 3, 'verb'),
('prove', '증명하다', 'To show that something is true', 'Prove your point with data.', 3, 'verb'),
('purchase', '구매하다', 'To buy something formally', 'Purchase the software online.', 3, 'verb'),
('reasonable', '합리적인', 'Fair and sensible', 'The price is very reasonable.', 3, 'adjective'),
('recommend', '추천하다', 'To suggest as being suitable', 'I recommend trying this approach.', 3, 'verb'),
('reliable', '신뢰할 수 있는', 'Consistently good in quality or ability', 'Choose a reliable supplier.', 3, 'adjective'),
('rely on', '의존하다', 'To depend on for support or help', 'You can rely on me.', 3, 'phrase'),
('remind', '상기시키다', 'To cause someone to remember something', 'Please remind me about the meeting.', 3, 'verb'),
('renew', '갱신하다', 'To extend the duration of something', 'Please renew your membership.', 3, 'verb'),
('respect', '존중하다', 'To treat someone or something with consideration', 'Always respect others'' opinions.', 3, 'verb'),
('responsible', '책임감 있는', 'Having a duty to deal with something', 'Be responsible for your actions.', 3, 'adjective'),
('reveal', '드러내다', 'To make previously unknown information known', 'The report revealed the truth.', 3, 'verb'),
('run out of', '다 떨어지다', 'To have no more of something left', 'We ran out of time.', 3, 'phrase'),
('satisfy', '만족시키다', 'To meet the expectations or needs of someone', 'We always try to satisfy customers.', 3, 'verb'),
('set aside', '따로 두다', 'To reserve something for a purpose', 'Set aside time for planning.', 3, 'phrase'),
('set off', '출발하다', 'To start a journey', 'We set off early to avoid traffic.', 3, 'phrase'),
('simple', '단순한', 'Easy to understand or do', 'Keep the message simple.', 3, 'adjective'),
('solve', '해결하다', 'To find an answer to a problem', 'We solved the issue quickly.', 3, 'verb'),
('specific', '구체적인', 'Clear and exact in detail', 'Please be more specific.', 3, 'adjective'),
('stable', '안정적인', 'Not likely to change or fail', 'The company has a stable income.', 3, 'adjective'),
('sum up', '요약하다', 'To state the main points briefly', 'Let me sum up the key findings.', 3, 'phrase'),
('survey', '조사하다', 'To examine and record information', 'We surveyed 500 customers.', 3, 'verb'),
('take away', '가져가다', 'To remove or eliminate something', 'What do you take away from this?', 3, 'phrase'),
('take care of', '돌보다', 'To look after or deal with something', 'I will take care of it.', 3, 'phrase'),
('take on', '맡다', 'To accept a duty or responsibility', 'She took on more projects this month.', 3, 'phrase'),
('take over', '인수하다', 'To assume control of something', 'He took over as team leader.', 3, 'phrase'),
('talented', '재능 있는', 'Having a natural ability to do well', 'She is a talented designer.', 3, 'adjective'),
('technical', '기술적인', 'Relating to specific skills or machinery', 'Technical knowledge is essential.', 3, 'adjective'),
('throw out', '버리다', 'To discard something no longer needed', 'Throw out any outdated information.', 3, 'phrase'),
('track', '추적하다', 'To follow or monitor progress', 'Track your spending every week.', 3, 'verb'),
('try out', '시도해보다', 'To test something to see if it works', 'Try out the new features.', 3, 'phrase'),
('turn around', '반전시키다', 'To improve a failing situation', 'We managed to turn around the project.', 3, 'phrase'),
('typical', '전형적인', 'Showing the usual characteristics', 'This is a typical problem.', 3, 'adjective'),
('unique', '독특한', 'Unlike anything else', 'Each product has a unique design.', 3, 'adjective'),
('up to date', '최신의', 'Including the most recent information', 'Keep the database up to date.', 3, 'phrase'),
('use up', '다 소진하다', 'To consume all of something', 'We used up all the paper.', 3, 'phrase'),
('various', '다양한', 'Of several different types', 'Various options are available.', 3, 'adjective'),
('volunteer', '자원봉사하다', 'To offer to do something without pay', 'She volunteers at the school on weekends.', 3, 'verb'),
('willing', '기꺼이 하는', 'Ready or eager to do something', 'Are you willing to work extra hours?', 3, 'adjective'),
('zoom in', '확대하다', 'To focus on a detail more closely', 'Zoom in on this section of the chart.', 3, 'phrase'),

-- ── difficulty 4 (B2 중상급) ──
('accessible', '손쉽게 이용할 수 있는', 'Able to be easily reached or used by people', 'Our service must be accessible to everyone.', 4, 'adjective'),
('acknowledge', '인정하다', 'To accept or admit the truth of something', 'Acknowledge mistakes and learn from them.', 4, 'verb'),
('adapt', '적응하다', 'To change to suit a new situation', 'Good leaders adapt to change quickly.', 4, 'verb'),
('adequate', '충분한', 'Good enough for a particular purpose', 'Ensure adequate resources are available.', 4, 'adjective'),
('adverse', '불리한', 'Preventing success or harmful in effect', 'Adverse weather affected the project.', 4, 'adjective'),
('advocate', '주창하다', 'To publicly support a cause or policy', 'She advocates for better work conditions.', 4, 'verb'),
('aftermath', '여파', 'The period following a difficult event', 'The aftermath of the crisis was challenging.', 4, 'noun'),
('aggregate', '집계', 'A whole formed by combining several elements', 'The aggregate score across all teams.', 4, 'noun'),
('alignment', '정렬', 'The state of being in agreement', 'We need alignment on priorities.', 4, 'noun'),
('allocate', '할당하다', 'To distribute resources or duties officially', 'Allocate the budget fairly across teams.', 4, 'verb'),
('alternative', '대안', 'A choice between two or more possibilities', 'Is there an alternative to this approach?', 4, 'noun'),
('ambiguous', '모호한', 'Having more than one possible meaning', 'The instructions were ambiguous.', 4, 'adjective'),
('anticipate', '예상하다', 'To expect or predict something', 'Anticipate problems before they arise.', 4, 'verb'),
('assumption', '가정', 'Something believed to be true without proof', 'Do not make assumptions without data.', 4, 'noun'),
('barrier', '장벽', 'Something that prevents progress', 'Language is a barrier in global business.', 4, 'noun'),
('benchmark', '기준점', 'A standard used to evaluate performance', 'Use industry benchmarks to measure success.', 4, 'noun'),
('bias', '편향', 'Unfair preference for or against something', 'Avoid bias in your analysis.', 4, 'noun'),
('bottleneck', '병목 현상', 'A point of congestion slowing progress', 'Identify and fix any bottlenecks in the process.', 4, 'noun'),
('catalyst', '촉매', 'Something that speeds up a process', 'Her feedback was a catalyst for change.', 4, 'noun'),
('clarify', '명확히 하다', 'To make something less confusing', 'Please clarify what you mean.', 4, 'verb'),
('collaborate', '협업하다', 'To work jointly on a project', 'Teams collaborate across departments.', 4, 'verb'),
('compelling', '설득력 있는', 'Very interesting or convincing', 'A compelling argument changes minds.', 4, 'adjective'),
('competent', '유능한', 'Having the necessary skills and knowledge', 'A competent leader earns trust.', 4, 'adjective'),
('comply', '준수하다', 'To act in accordance with rules', 'All employees must comply with the policy.', 4, 'verb'),
('comprehensive', '포괄적인', 'Including all or nearly all aspects', 'We need a comprehensive plan.', 4, 'adjective'),
('conceptual', '개념적인', 'Relating to concepts or ideas', 'A conceptual framework helps organize thinking.', 4, 'adjective'),
('concise', '간결한', 'Giving information clearly and briefly', 'Keep your report concise and to the point.', 4, 'adjective'),
('consistent', '일관된', 'Always behaving or performing the same way', 'Consistent effort leads to success.', 4, 'adjective'),
('constraint', '제약', 'A limitation or restriction', 'Budget constraints limit our options.', 4, 'noun'),
('context', '맥락', 'The circumstances surrounding something', 'Understand the context before deciding.', 4, 'noun'),
('contingency', '비상 대책', 'A plan for an unexpected event', 'Have a contingency plan ready.', 4, 'noun'),
('controversy', '논란', 'Disagreement involving different opinions', 'The decision sparked controversy.', 4, 'noun'),
('credibility', '신뢰성', 'The quality of being trusted and believed', 'Credibility is built through honesty.', 4, 'noun'),
('criteria', '기준', 'Standards used to judge something', 'Define the criteria for success.', 4, 'noun'),
('decisive', '결단력 있는', 'Settling an issue or having the ability to decide', 'A decisive manager makes quick choices.', 4, 'adjective'),
('deliberate', '의도적인', 'Done consciously and intentionally', 'It was a deliberate decision.', 4, 'adjective'),
('demonstrate', '증명하다', 'To show evidence of something clearly', 'Demonstrate your value through results.', 4, 'verb'),
('depreciation', '감가상각', 'A reduction in value over time', 'Account for asset depreciation.', 4, 'noun'),
('derive', '도출하다', 'To obtain something from a source', 'Derive insights from the data.', 4, 'verb'),
('discrepancy', '불일치', 'A difference between two things', 'There is a discrepancy in the report.', 4, 'noun'),
('disparity', '격차', 'A great difference between things', 'Address the salary disparity.', 4, 'noun'),
('documentation', '문서화', 'The process of recording information', 'Good documentation prevents confusion.', 4, 'noun'),
('dominant', '지배적인', 'Most important or powerful', 'They hold a dominant position.', 4, 'adjective'),
('due diligence', '실사', 'A careful investigation before a decision', 'We performed full due diligence.', 4, 'noun'),
('efficiency', '효율성', 'Achieving maximum output with minimum waste', 'Improve efficiency by automating tasks.', 4, 'noun'),
('elaborate', '자세히 설명하다', 'To explain in more detail', 'Could you elaborate on that point?', 4, 'verb'),
('empirical', '경험적인', 'Based on observation and experiment', 'We need empirical evidence.', 4, 'adjective'),
('enforce', '집행하다', 'To make people obey a rule or law', 'Enforce company policies consistently.', 4, 'verb'),
('enhance', '향상시키다', 'To improve the quality of something', 'Enhance the user experience.', 4, 'verb'),
('equitable', '공평한', 'Fair and impartial', 'Create an equitable work environment.', 4, 'adjective'),
('execute', '실행하다', 'To carry out or implement a plan', 'Execute the strategy step by step.', 4, 'verb'),
('explicit', '명시적인', 'Stated clearly without ambiguity', 'Be explicit about your expectations.', 4, 'adjective'),
('facilitate', '촉진하다', 'To make an action or process easier', 'Technology facilitates communication.', 4, 'verb'),
('feasible', '실현 가능한', 'Possible to do or achieve', 'Is this plan feasible within the budget?', 4, 'adjective'),
('flexible', '유연한', 'Able to change according to circumstances', 'Stay flexible in your approach.', 4, 'adjective'),
('fluctuate', '변동하다', 'To change irregularly', 'Prices tend to fluctuate seasonally.', 4, 'verb'),
('framework', '체계', 'A structure for organizing ideas', 'Use a strategic framework.', 4, 'noun'),
('fundamental', '근본적인', 'Of central importance', 'Trust is a fundamental value.', 4, 'adjective'),
('generate', '창출하다', 'To produce or create something', 'Generate revenue through new channels.', 4, 'verb'),
('governance', '지배구조', 'The system by which something is controlled', 'Strong governance prevents misuse.', 4, 'noun'),
('highlight', '강조하다', 'To draw special attention to something', 'Highlight the key issues in your report.', 4, 'verb'),
('holistic', '전체적인', 'Considering something as a whole', 'Take a holistic approach to health.', 4, 'adjective'),
('impact', '영향', 'A marked effect or influence', 'Measure the impact of the change.', 4, 'noun'),
('implement', '구현하다', 'To put a plan or decision into effect', 'Implement the feedback from users.', 4, 'verb'),
('implication', '함의', 'A likely consequence or meaning', 'Consider the implications of this choice.', 4, 'noun'),
('incentive', '인센티브', 'Something that motivates action', 'Offer incentives to top performers.', 4, 'noun'),
('incorporate', '통합하다', 'To include something as part of a whole', 'Incorporate new ideas into the plan.', 4, 'verb'),
('indicator', '지표', 'A sign that shows a situation or trend', 'Use KPIs as performance indicators.', 4, 'noun'),
('initiative', '주도권', 'A new plan designed to achieve a goal', 'Launch a new customer initiative.', 4, 'noun'),
('insight', '통찰력', 'A deep understanding of something', 'Data analysis provides useful insights.', 4, 'noun'),
('integrate', '통합하다', 'To combine elements into a whole', 'Integrate the new system with existing ones.', 4, 'verb'),
('integrity', '무결성', 'The quality of being honest and having principles', 'Integrity is non-negotiable.', 4, 'noun'),
('interaction', '상호작용', 'Communication or direct involvement', 'Increase customer interaction.', 4, 'noun'),
('internal', '내부의', 'Existing inside an organization', 'Handle internal conflicts professionally.', 4, 'adjective'),
('investigation', '조사', 'A formal examination of facts', 'Conduct an investigation into the issue.', 4, 'noun'),
('leverage', '활용하다', 'To use resources to maximum advantage', 'Leverage technology to save time.', 4, 'verb'),
('limitation', '한계', 'A restriction or weakness', 'Every approach has limitations.', 4, 'noun'),
('mandate', '권한', 'An official instruction to do something', 'We have a mandate to cut costs.', 4, 'noun'),
('mechanism', '메커니즘', 'A system or process for achieving something', 'Create a feedback mechanism.', 4, 'noun'),
('methodology', '방법론', 'A system of methods used in an activity', 'Choose the right methodology.', 4, 'noun'),
('milestone', '이정표', 'A significant event or achievement', 'We reached a major milestone.', 4, 'noun'),
('mitigate', '완화하다', 'To make something less severe', 'Mitigate risks before they occur.', 4, 'verb'),
('monitor', '모니터링하다', 'To observe and check progress', 'Monitor the system daily.', 4, 'verb'),
('objective', '목표', 'An aim or goal to be achieved', 'Define clear objectives for the team.', 4, 'noun'),
('optimize', '최적화하다', 'To make the best use of a situation', 'Optimize your workflow for efficiency.', 4, 'verb'),
('outcome', '결과', 'The end result of a process or action', 'Measure the outcome of each decision.', 4, 'noun'),
('outline', '개요를 잡다', 'To describe the main points briefly', 'Outline the project scope clearly.', 4, 'verb'),
('parameter', '매개변수', 'A numerical factor that defines a system', 'Set the parameters before running the test.', 4, 'noun'),
('perspective', '관점', 'A particular way of considering something', 'Gain a broader perspective.', 4, 'noun'),
('portfolio', '포트폴리오', 'A range of investments or work samples', 'Diversify your investment portfolio.', 4, 'noun'),
('pragmatic', '실용적인', 'Dealing with things in a practical way', 'Take a pragmatic approach.', 4, 'adjective'),
('precedent', '선례', 'An earlier case used as a guide', 'This decision sets a precedent.', 4, 'noun'),
('preliminary', '예비의', 'Happening before the main event', 'We have preliminary results.', 4, 'adjective'),
('prioritize', '우선시하다', 'To determine the order of importance', 'Prioritize tasks by urgency.', 4, 'verb'),
('protocol', '프로토콜', 'A set of rules governing behavior', 'Follow the company protocol.', 4, 'noun'),
('quantify', '수치화하다', 'To express as a number or quantity', 'Quantify the results where possible.', 4, 'verb'),
('rationale', '근거', 'The reasons for a decision or action', 'Explain the rationale behind the decision.', 4, 'noun'),
('realistic', '현실적인', 'Having a sensible understanding of things', 'Set realistic expectations.', 4, 'adjective'),
('reinforce', '강화하다', 'To strengthen an idea or structure', 'Reinforce positive behaviors.', 4, 'verb'),
('resilience', '회복력', 'The ability to recover from difficulties', 'Build resilience in your team.', 4, 'noun'),
('retain', '유지하다', 'To keep or continue to have something', 'Retain top talent with good culture.', 4, 'verb'),
('risk assessment', '위험 평가', 'The identification of potential problems', 'Complete a risk assessment first.', 4, 'noun'),
('roadmap', '로드맵', 'A strategic plan for the future', 'Share the product roadmap with the team.', 4, 'noun'),
('robust', '강력한', 'Strong and healthy; unlikely to fail', 'We need a robust solution.', 4, 'adjective'),
('scalable', '확장 가능한', 'Able to grow without losing performance', 'Build a scalable system.', 4, 'adjective'),
('scope', '범위', 'The extent of the subject dealt with', 'Define the scope of the project.', 4, 'noun'),
('scrutinize', '면밀히 검토하다', 'To examine something very carefully', 'Scrutinize the data before publishing.', 4, 'verb'),
('seamless', '매끄러운', 'Smooth and without problems', 'Create a seamless user experience.', 4, 'adjective'),
('significant', '중요한', 'Important or meaningful', 'This is a significant change.', 4, 'adjective'),
('straightforward', '간단명료한', 'Easy to do or understand', 'The process is straightforward.', 4, 'adjective'),
('streamline', '간소화하다', 'To make simpler and more efficient', 'Streamline the approval process.', 4, 'verb'),
('substantial', '상당한', 'Of considerable size or importance', 'There was a substantial increase.', 4, 'adjective'),
('sustainable', '지속 가능한', 'Able to be maintained long-term', 'Build a sustainable business model.', 4, 'adjective'),
('synthesis', '종합', 'A combination of elements into a whole', 'The report is a synthesis of research.', 4, 'noun'),
('tangible', '실질적인', 'Clear and definite; able to be touched', 'Deliver tangible results.', 4, 'adjective'),
('threshold', '임계값', 'A level at which something begins', 'Set a minimum performance threshold.', 4, 'noun'),
('timeline', '타임라인', 'A schedule showing when events occur', 'Share a project timeline.', 4, 'noun'),
('trade-off', '트레이드오프', 'A balance between two desirable qualities', 'Every decision involves a trade-off.', 4, 'noun'),
('transparency', '투명성', 'Openness and clarity about actions', 'Transparency builds trust.', 4, 'noun'),
('underlying', '근본적인', 'Fundamental to or below the surface', 'Find the underlying cause.', 4, 'adjective'),
('underscore', '강조하다', 'To emphasize the importance of something', 'These results underscore the need for change.', 4, 'verb'),
('unprecedented', '전례 없는', 'Never done or known before', 'This is an unprecedented situation.', 4, 'adjective'),
('upgrade', '업그레이드하다', 'To improve to a higher standard or quality', 'Upgrade the software this week.', 4, 'verb'),
('validate', '검증하다', 'To demonstrate or support with evidence', 'Validate your assumptions with testing.', 4, 'verb'),
('viable', '실행 가능한', 'Capable of working successfully', 'Is this a viable long-term solution?', 4, 'adjective'),
('vision', '비전', 'A long-term aim or goal', 'Communicate the company vision clearly.', 4, 'noun'),

-- ── difficulty 5 (C1 고급) ──
('acumen', '통찰력', 'The ability to make good judgments quickly', 'She demonstrated strong business acumen.', 5, 'noun'),
('ameliorate', '개선하다', 'To make something bad better', 'Steps to ameliorate the situation were taken.', 5, 'verb'),
('articulate', '명확히 표현하다', 'To express ideas clearly and effectively', 'Articulate your vision to inspire others.', 5, 'verb'),
('astute', '명민한', 'Having a clever understanding of situations', 'An astute observer notices small details.', 5, 'adjective'),
('augment', '강화하다', 'To increase the value or amount of something', 'Augment human capability with AI tools.', 5, 'verb'),
('circumvent', '우회하다', 'To find a way around a rule or problem', 'They tried to circumvent the regulations.', 5, 'verb'),
('coherent', '일관된', 'Logical and consistent', 'Present a coherent argument.', 5, 'adjective'),
('cognizant', '인식하고 있는', 'Having knowledge or awareness of something', 'Be cognizant of cultural differences.', 5, 'adjective'),
('commensurate', '상응하는', 'In proportion to something', 'Salary commensurate with experience.', 5, 'adjective'),
('conjecture', '추측', 'An opinion formed without definite proof', 'That is pure conjecture without data.', 5, 'noun'),
('corroborate', '확증하다', 'To confirm or give support to a statement', 'Data helps corroborate the hypothesis.', 5, 'verb'),
('delineate', '묘사하다', 'To describe or portray something precisely', 'Delineate the roles within the team.', 5, 'verb'),
('diligence', '성실함', 'Careful and persistent effort', 'Success comes from diligence.', 5, 'noun'),
('discern', '식별하다', 'To recognize or find out', 'Discern the root cause of the issue.', 5, 'verb'),
('disseminate', '보급하다', 'To spread information widely', 'Disseminate the findings to all teams.', 5, 'verb'),
('efficacy', '효력', 'The ability to produce the desired result', 'Test the efficacy of the new process.', 5, 'noun'),
('elucidate', '해명하다', 'To make something clear by explaining', 'Please elucidate the key risks.', 5, 'verb'),
('empirically', '경험적으로', 'Based on evidence and observation', 'Prove it empirically through testing.', 5, 'adverb'),
('encompass', '포함하다', 'To include a wide range of things', 'The strategy encompasses all regions.', 5, 'verb'),
('engender', '야기하다', 'To cause or give rise to a feeling or situation', 'Good communication engenders trust.', 5, 'verb'),
('equivocal', '모호한', 'Having two possible meanings; uncertain', 'His answer was equivocal.', 5, 'adjective'),
('exacerbate', '악화시키다', 'To make a problem worse', 'Poor communication exacerbates conflicts.', 5, 'verb'),
('expedient', '편의적인', 'Convenient though possibly improper', 'An expedient solution may cause problems later.', 5, 'adjective'),
('explicit', '명백한', 'Stated clearly and in detail', 'Set explicit performance standards.', 5, 'adjective'),
('extrapolate', '추론하다', 'To extend known data into unknown areas', 'Extrapolate the trend for the next quarter.', 5, 'verb'),
('fallacious', '오류가 있는', 'Based on a mistaken belief', 'Avoid fallacious arguments.', 5, 'adjective'),
('holistic', '총체적인', 'Relating to the whole rather than parts', 'A holistic strategy considers all factors.', 5, 'adjective'),
('immutable', '불변의', 'Unchanging over time', 'Certain values should be immutable.', 5, 'adjective'),
('imperative', '필수적인', 'Of vital importance or urgency', 'It is imperative to act now.', 5, 'adjective'),
('inadvertent', '의도치 않은', 'Not resulting from deliberate planning', 'An inadvertent error caused the delay.', 5, 'adjective'),
('infer', '추론하다', 'To deduce from evidence', 'Infer conclusions from the data.', 5, 'verb'),
('inherent', '내재적인', 'Existing in something as a permanent quality', 'There are inherent risks in any venture.', 5, 'adjective'),
('meticulous', '꼼꼼한', 'Showing great attention to detail', 'Meticulous planning prevents mistakes.', 5, 'adjective'),
('nuanced', '미묘한', 'Characterized by subtle shades of meaning', 'Give a nuanced response to complex issues.', 5, 'adjective'),
('obsolete', '구식의', 'No longer produced or used', 'Outdated systems become obsolete quickly.', 5, 'adjective'),
('paradigm shift', '패러다임 전환', 'A fundamental change in approach', 'AI represents a paradigm shift.', 5, 'noun'),
('pervasive', '만연한', 'Spreading widely through something', 'Mobile technology is now pervasive.', 5, 'adjective'),
('proliferate', '확산되다', 'To increase rapidly in number', 'Digital platforms continue to proliferate.', 5, 'verb'),
('provoke', '유발하다', 'To cause a reaction or feeling', 'Bold statements provoke discussion.', 5, 'verb'),
('reconcile', '화해시키다', 'To restore friendly relations or make consistent', 'Reconcile conflicting priorities.', 5, 'verb'),
('reiterate', '반복하다', 'To say something again for emphasis', 'I want to reiterate the main point.', 5, 'verb'),
('repercussion', '영향', 'An unintended consequence of an action', 'Consider the repercussions of the decision.', 5, 'noun'),
('rhetoric', '수사학', 'Language designed to persuade', 'Good rhetoric moves people to act.', 5, 'noun'),
('rigorous', '엄밀한', 'Extremely thorough and careful', 'Apply rigorous testing standards.', 5, 'adjective'),
('salient', '두드러진', 'Most important or most noticeable', 'Identify the salient features.', 5, 'adjective'),
('scrutiny', '면밀한 검토', 'Critical observation or examination', 'Financial records are under scrutiny.', 5, 'noun'),
('substantiate', '입증하다', 'To provide evidence to support a claim', 'Substantiate your claims with data.', 5, 'verb'),
('systemic', '체계적인', 'Relating to a whole system', 'Address systemic issues, not just symptoms.', 5, 'adjective'),
('taxonomy', '분류법', 'A system for classifying things', 'Use a clear taxonomy for your data.', 5, 'noun'),
('tenuous', '희박한', 'Very weak or slight', 'The connection is tenuous at best.', 5, 'adjective'),
('transparency', '투명성', 'The quality of being open and honest', 'Transparency is key to good leadership.', 5, 'noun'),
('unambiguous', '명확한', 'Not open to more than one interpretation', 'Give unambiguous instructions.', 5, 'adjective'),
('ubiquitous', '어디에나 있는', 'Present everywhere or very common', 'Smartphones are now ubiquitous.', 5, 'adjective'),
('vanguard', '선두', 'The leading position in a trend or movement', 'We are at the vanguard of innovation.', 5, 'noun'),
('verbose', '장황한', 'Using more words than needed', 'Avoid verbose writing in reports.', 5, 'adjective')

ON CONFLICT (word) DO NOTHING;
